- Obsoleted sh init scripts     - MM_INIT_TYPE=sh will no longer work

diff --git a/trunk/gar-minimyth/script/meta/minimyth/files/source/initrd/sbin/init b/trunk/gar-minimyth/script/meta/minimyth/files/source/initrd/sbin/init
--- a/trunk/gar-minimyth/script/meta/minimyth/files/source/initrd/sbin/init
+++ b/trunk/gar-minimyth/script/meta/minimyth/files/source/initrd/sbin/init
@@ -12,9 +12,8 @@ cd /rootfs
 /bin/echo -n "start date and time: " >> /init.log
 /bin/date -u +'%Y-%m-%d %H:%M:%S %Z' >> /init.log
 
-if /usr/bin/test ! "${MM_INIT_TYPE}" = 'perl' && \
-   /usr/bin/test ! "${MM_INIT_TYPE}" = 'sh'   ; then
-    MM_INIT_TYPE=${MM_INIT_TYPE:-'perl'}
+if /usr/bin/test -z "${MM_INIT_TYPE}" ; then
+    MM_INIT_TYPE='perl'
 fi
 
 # Save boot line options that we need later.
@@ -23,10 +22,13 @@ set | /bin/grep -e '^BOOT_IMAGE=' >> /etc/conf.d/boot
 set | /bin/grep -e '^initrd='     >> /etc/conf.d/boot
 set | /bin/grep -e '^MM_'         >> /etc/conf.d/boot
 
-if   /usr/bin/test ${MM_INIT_TYPE} = 'perl' ; then
+if   /usr/bin/test ${MM_INIT_TYPE} = 'perl'        ; then
     /bin/ln -s /etc/inittab.perl /etc/inittab
-elif /usr/bin/test ${MM_INIT_TYPE} = 'sh'   ; then
+elif /usr/bin/test ${MM_INIT_TYPE} = 'sh.obsolete' ; then
     /bin/ln -s /etc/inittab.sh   /etc/inittab
+else
+    /bin/echo "error: MM_INIT_TYPE=${MM_INIT_TYPE} is invalid."
+    exit 1
 fi
 
 # Change root to the read-write root file system and start the real init.
