perforce changeset 1110

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions
@@ -52,7 +52,7 @@ mm_url_file_get() {
     /usr/bin/test -n "${LOCAL_DIR}" && /usr/bin/test ! -d "${LOCAL_DIR}" && return
 
     /bin/cp "${REMOTE_FILE}" "${LOCAL_FILE}" || return
-    /usr/bin/logger -t minimyth -p "local0.info" "file:/${REMOTE_FILE} retrieved."
+    /usr/bin/logger -s -t minimyth -p "local0.info" "file:/${REMOTE_FILE} retrieved."
 }
 
 mm_url_http_get() {
@@ -68,7 +68,7 @@ mm_url_http_get() {
 
     /usr/bin/wget "http://${REMOTE_SERVER}/${REMOTE}" -O "${LOCAL_FILE}" || return
 
-    /usr/bin/logger -t minimyth -p "local0.info" "http://${REMOTE_SERVER}/${REMOTE_FILE} retrieved."
+    /usr/bin/logger -s -t minimyth -p "local0.info" "http://${REMOTE_SERVER}/${REMOTE_FILE} retrieved."
 }
 
 mm_url_tftp_get() {
@@ -84,7 +84,7 @@ mm_url_tftp_get() {
 
     /usr/bin/tftp -g -r "${REMOTE_FILE}" -l "${LOCAL_FILE}" "${REMOTE_SERVER}" || return
 
-    /usr/bin/logger -t minimyth -p "local0.info" "tftp://${REMOTE_SERVER}/${REMOTE_FILE} retrieved."
+    /usr/bin/logger -s -t minimyth -p "local0.info" "tftp://${REMOTE_SERVER}/${REMOTE_FILE} retrieved."
 }
 
 mm_url_conf_get() {
@@ -92,45 +92,55 @@ mm_url_conf_get() {
     local REMOTE_FILE=$2
     local REMOTE_SERVER=$3
 
+    local HOSTNAME
     local FILE_GOT
     local LOCAL_DIR
+    local REMOTE_FILE_ALT
     local TMP_FILE
+
+    HOSTNAME=`/bin/hostname`
 
     LOCAL_DIR=`/bin/echo "${LOCAL_FILE}" | /bin/sed -e 's%[^/]*$%%' -e 's%/$%%'`
     /usr/bin/test -n "${LOCAL_DIR}" && /bin/mkdir -p "${LOCAL_DIR}"
     /usr/bin/test -n "${LOCAL_DIR}" && /usr/bin/test ! -d "${LOCAL_DIR}" && return
 
-    TMP_FILE="${LOCAL_FILE}~"
+    REMOTE_FILE_ALT=`/bin/echo ${REMOTE_FILE} \
+        | /bin/sed -e 's%^/*%%'               \
+        | /bin/sed -e 's%/*$%%'               \
+        | /bin/sed -e 's%//*%/%g'             \
+        | /bin/sed -e 's%/%+%'`
 
+    TMP_FILE="${LOCAL_FILE}~"
+    
     /bin/rm -f "${TMP_FILE}"
     FILE_GOT=
     if /usr/bin/test -d "/minimyth" ; then
-        /usr/bin/test -z "${FILE_GOT}" && /usr/bin/test -n "`/bin/hostname`" && 
-            /usr/bin/test -e "/minimyth/conf-rw/`/bin/hostname`+${REMOTE_FILE}" &&
-	    /bin/cp          "/minimyth/conf-rw/`/bin/hostname`+${REMOTE_FILE}"                "${TMP_FILE}"                     && 
-	    FILE_GOT="'file:/minimyth/conf/`hostname`/${REMOTE_FILE}' retrieved."
-        /usr/bin/test -z "${FILE_GOT}" && /usr/bin/test -n "`/bin/hostname`" &&
-            /usr/bin/test -e "/minimyth/conf/`/bin/hostname`/${REMOTE_FILE}"    &&
-	    /bin/cp          "/minimyth/conf/`/bin/hostname`/${REMOTE_FILE}"                   "${TMP_FILE}"                     && 
-	    FILE_GOT="'file:/minimyth/conf/`hostname`/${REMOTE_FILE}' retrieved."
+        /usr/bin/test -z "${FILE_GOT}" && /usr/bin/test -n "${HOSTNAME}" && 
+            /usr/bin/test -e "/minimyth/conf-rw/${HOSTNAME}+${REMOTE_FILE_ALT}" &&
+	    /bin/cp          "/minimyth/conf-rw/${HOSTNAME}+${REMOTE_FILE_ALT}"                "${TMP_FILE}"                     && 
+	    FILE_GOT="'file:/minimyth/conf-rw/${HOSTNAME}+${REMOTE_FILE_ALT}' retrieved."
+        /usr/bin/test -z "${FILE_GOT}" && /usr/bin/test -n "${HOSTNAME}" &&
+            /usr/bin/test -e "/minimyth/conf/${HOSTNAME}/${REMOTE_FILE}"    &&
+	    /bin/cp          "/minimyth/conf/${HOSTNAME}/${REMOTE_FILE}"                       "${TMP_FILE}"                     && 
+	    FILE_GOT="'file:/minimyth/conf/${HOSTNAME}/${REMOTE_FILE}' retrieved."
         /usr/bin/test -z "${FILE_GOT}" &&
             /usr/bin/test -e "/minimyth/conf/default/${REMOTE_FILE}"            &&
 	    /bin/cp          "/minimyth/conf/default/${REMOTE_FILE}"                           "${TMP_FILE}"                     &&
 	    FILE_GOT="'file:/minimyth/conf/default/${REMOTE_FILE}' retrieved."
     else
-        /usr/bin/test -z "${FILE_GOT}" && /usr/bin/test -n "`/bin/hostname`" &&
-            /usr/bin/tftp -g -r "${MM_TFTP_ROOTDIR}/conf-rw/`/bin/hostname`+${REMOTE_FILE}" -l "${TMP_FILE}" "${MM_TFTP_SERVER}" &&
-	    FILE_GOT="'tftp://${MM_TFTP_SERVER}/${MM_TFTP_ROOTDIR}/conf-rw/`hostname`+${REMOTE_FILE}' retrieved."
-        /usr/bin/test -z "${FILE_GOT}" && /usr/bin/test -n "`/bin/hostname`" &&
-            /usr/bin/tftp -g -r "${MM_TFTP_ROOTDIR}/conf/`/bin/hostname`/${REMOTE_FILE}"    -l "${TMP_FILE}" "${MM_TFTP_SERVER}" &&
-	    FILE_GOT="'tftp://${MM_TFTP_SERVER}/${MM_TFTP_ROOTDIR}/conf/`hostname`/${REMOTE_FILE}' retrieved."
+        /usr/bin/test -z "${FILE_GOT}" && /usr/bin/test -n "${HOSTNAME}" &&
+            /usr/bin/tftp -g -r "${MM_TFTP_ROOTDIR}/conf-rw/${HOSTNAME}+${REMOTE_FILE_ALT}" -l "${TMP_FILE}" "${MM_TFTP_SERVER}" &&
+	    FILE_GOT="'tftp://${MM_TFTP_SERVER}/${MM_TFTP_ROOTDIR}/conf-rw/${HOSTNAME}+${REMOTE_FILE_ALT}' retrieved."
+        /usr/bin/test -z "${FILE_GOT}" && /usr/bin/test -n "${HOSTNAME}" &&
+            /usr/bin/tftp -g -r "${MM_TFTP_ROOTDIR}/conf/${HOSTNAME}/${REMOTE_FILE}"        -l "${TMP_FILE}" "${MM_TFTP_SERVER}" &&
+	    FILE_GOT="'tftp://${MM_TFTP_SERVER}/${MM_TFTP_ROOTDIR}/conf/${HOSTNAME}/${REMOTE_FILE}' retrieved."
         /usr/bin/test -z "${FILE_GOT}" && 
             /usr/bin/tftp -g -r "${MM_TFTP_ROOTDIR}/conf/default/${REMOTE_FILE}"            -l "${TMP_FILE}" "${MM_TFTP_SERVER}" &&
 	    FILE_GOT="'tftp://${MM_TFTP_SERVER}/${MM_TFTP_ROOTDIR}/conf/default/${REMOTE_FILE}' retrieved."
     fi
     if /usr/bin/test -n "${FILE_GOT}" ; then
         /bin/mv -f "${TMP_FILE}" "${LOCAL_FILE}"
-        /usr/bin/logger -t minimyth -p "local0.info" "${FILE_GOT}"
+        /usr/bin/logger -s -t minimyth -p "local0.info" "${FILE_GOT}"
     fi
     /bin/rm -f "${TMP_FILE}"
     if /usr/bin/test -z "${FILE_GOT}" ; then
@@ -169,7 +179,7 @@ mm_url_dist_get() {
     fi
     if /usr/bin/test -n "${FILE_GOT}" ; then
         /bin/mv -f "${TMP_FILE}" "${LOCAL_FILE}"
-        /usr/bin/logger -t minimyth -p "local0.info" "${FILE_GOT}"
+        /usr/bin/logger -s -t minimyth -p "local0.info" "${FILE_GOT}"
     fi
     /bin/rm -f "${TMP_FILE}"
     if /usr/bin/test -z "${FILE_GOT}" ; then
@@ -212,35 +222,41 @@ mm_conf_put() {
     local HOSTNAME=`/bin/hostname`
 
     if /usr/bin/test ! -f "${LOCAL_FILE}" ; then
-        /usr/bin/logger -t minimyth -p "local0.error"  \
+        /usr/bin/logger -s -t minimyth -p "local0.error"  \
             "cannot post conf file '${LOCAL_FILE}' because file not found."
         /bin/false
         return
     fi
     if /usr/bin/test -z "${HOSTNAME}" ; then
-        /usr/bin/logger -t minimyth -p "local0.error"  \
+        /usr/bin/logger -s -t minimyth -p "local0.error"  \
             "cannot post conf file '${LOCAL_FILE}' because hostname is unknown."
         /bin/false
         return
     fi
 
+    REMOTE_FILE=`/bin/echo ${REMOTE_FILE} \
+        | /bin/sed -e 's%^/*%%'           \
+        | /bin/sed -e 's%/*$%%'           \
+        | /bin/sed -e 's%//*%/%g'         \
+        | /bin/sed -e 's%/%+%'`
+
     if /usr/bin/test -d "/minimyth" ; then
         mkdir -p "/minimyth/conf-rw"
         if /bin/cp -f         "${LOCAL_FILE}"             "/minimyth/conf-rw/${HOSTNAME}+${REMOTE_FILE}"                     ; then
-            /usr/bin/logger -t minimyth -p "local0.info"  \
+            /usr/bin/logger -s -t minimyth -p "local0.info"  \
                 "'file:/minimyth/conf-rw/${HOSTNAME}+${REMOTE_FILE}' posted."
         else
-            /usr/bin/logger -t minimyth -p "local0.error" \
+            /usr/bin/logger -s -t minimyth -p "local0.error" \
                 "'file:/minimyth/conf-rw/${HOSTNAME}+${REMOTE_FILE}' failed to post."
             /bin/false
             return
         fi
     else
        if /usr/bin/tftp -p -l "${LOCAL_FILE}" -r "${MM_TFTP_ROOTDIR}/conf-rw/${HOSTNAME}+${REMOTE_FILE}" "${MM_TFTP_SERVER}" ; then
-            /usr/bin/logger -t minimyth -p "local0.info"  \
+            /usr/bin/logger -s -t minimyth -p "local0.info"  \
                 "'tftp://${MM_TFTP_SERVER}/${MM_TFTP_ROOTDIR}/conf-rw/${HOSTNAME}+${REMOTE_FILE}' posted."
        else
-            /usr/bin/logger -t minimyth -p "local0.error" \
+            /usr/bin/logger -s -t minimyth -p "local0.error" \
                 "'tftp://${MM_TFTP_SERVER}/${MM_TFTP_ROOTDIR}/conf-rw/${HOSTNAME}+${REMOTE_FILE}' failed to post."
             /bin/false
             return
@@ -250,11 +266,18 @@ mm_conf_put() {
 
 mm_game_restore() {
 
+    local FILE
     local REMOTE_FILE
+    local LOCAL_DIR
     local LOCAL_FILE
 
-    REMOTE_FILE="game.tar"
-    LOCAL_FILE="/home/minimyth/game.tar~"
+    FILE="game.tar"
+    REMOTE_FILE="${FILE}"
+    LOCAL_DIR="${HOME}/tmp"
+    LOCAL_FILE="${LOCAL_DIR}/${FILE}"
+
+    /usr/bin/test -n "${LOCAL_DIR}" && /bin/mkdir -p "${LOCAL_DIR}"
+    /usr/bin/test -n "${LOCAL_DIR}" && /usr/bin/test ! -d "${LOCAL_DIR}" && return
 
     /bin/rm -f "${LOCAL_FILE}"
 
@@ -271,15 +294,16 @@ mm_game_restore() {
 
 mm_game_save() {
 
-    local LOCAL_FILE
+    local FILE
     local REMOTE_FILE
-
-    LOCAL_FILE="/home/minimyth/game.tar~"
-    REMOTE_FILE="game.tar"
-
     local LOCAL_DIR
-    LOCAL_DIR=`/bin/echo "${LOCAL_FILE}" | /bin/sed -e 's%[^/]*$%%' -e 's%/$%%'`
-    LOCAL_DIR=`/bin/echo "${LOCAL_FILE}" | /bin/sed -e 's%[^/]*$%%' -e 's%/$%%'`
+    local LOCAL_FILE
+
+    FILE="game.tar"
+    REMOTE_FILE="${FILE}"
+    LOCAL_DIR="${HOME}/tmp"
+    LOCAL_FILE="${LOCAL_DIR}/${FILE}"
+
     /usr/bin/test -n "${LOCAL_DIR}" && /bin/mkdir -p "${LOCAL_DIR}"
     /usr/bin/test -n "${LOCAL_DIR}" && /usr/bin/test ! -d "${LOCAL_DIR}" && return
 
@@ -316,8 +340,8 @@ mm_game_save() {
         /bin/tar -cf "${LOCAL_FILE}" ${GAME_SAVE_LIST} || /bin/rm -f "${LOCAL_FILE}"
         IFS=${IFS_SAVE}
         if /usr/bin/test ! -e "${LOCAL_FILE}" ; then
-            /usr/bin/logger -t minimyth -p "local0.error" \
-                "failed to create game configuration files tarball."
+            /usr/bin/logger -s -t minimyth -p "local0.error" \
+                "failed to create game files tarball."
             /bin/false
             return
         fi
@@ -330,6 +354,186 @@ mm_game_save() {
             /bin/rm -f "${LOCAL_FILE}"
         fi
     fi
+}
+
+mm_codecs_fetch_and_save() {
+
+    local FILE
+    local REMOTE_FILE
+    local LOCAL_DIR
+    local LOCAL_FILE
+
+    local CODECS_BASE
+    local CODECS_FILE
+    local CODECS_URL
+
+    FILE="codecs.sfs"
+    REMOTE_FILE="${FILE}"
+    LOCAL_DIR="${HOME}/tmp"
+    LOCAL_FILE="${LOCAL_DIR}/${FILE}"
+
+    /usr/bin/test -n "${LOCAL_DIR}" && /bin/mkdir -p "${LOCAL_DIR}"
+    /usr/bin/test -n "${LOCAL_DIR}" && /usr/bin/test ! -d "${LOCAL_DIR}" && return
+
+    CODECS_BASE="essential-20061022"
+    CODECS_FILE="${CODECS_BASE}.tar.bz2"
+    CODECS_URL="http://www.mplayerhq.hu/MPlayer/releases/codecs/${CODECS_FILE}"
+    /bin/rm -rf "${LOCAL_DIR}/${CODECS_BASE}"
+    /bin/rm -f "${LOCAL_DIR}/${CODECS_FILE}"
+    cd "${LOCAL_DIR}"
+    /usr/bin/wget "${CODECS_URL}" -O "${CODECS_FILE}"
+    if /usr/bin/test $? -ne 0 ; then
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to create the codecs file because no codecs were retrieved."
+        cd "${HOME}"
+        /bin/rm -rf "${LOCAL_DIR}/${CODECS_BASE}"
+        /bin/rm -f "${LOCAL_DIR}/${CODECS_FILE}"
+        /bin/false
+        return
+    fi
+    /bin/tar -jxf "${CODECS_FILE}"
+    /bin/rm -f "${CODECS_FILE}"
+
+    if /usr/bin/test ! -d "${LOCAL_DIR}/${CODECS_BASE}" || /usr/bin/test `ls -1 "${LOCAL_DIR}/${CODECS_BASE}" | /usr/bin/wc -l` -eq 0 ; then
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to create the codecs file because retrieved codecs file was empty."
+        cd "${HOME}"
+        /bin/rm -rf "${LOCAL_DIR}/${CODECS_BASE}"
+        /bin/false
+        return
+    fi
+
+    cd "${LOCAL_DIR}"
+    /bin/chown `/usr/bin/id -u`:`/usr/bin/id -g` ${LOCAL_DIR}/${CODECS_BASE}
+    /bin/chmod 755                               ${LOCAL_DIR}/${CODECS_BASE}
+    /bin/chown `/usr/bin/id -u`:`/usr/bin/id -g` ${LOCAL_DIR}/${CODECS_BASE}/*
+    /bin/chmod 644                               ${LOCAL_DIR}/${CODECS_BASE}/*
+
+    /bin/rm -f "${LOCAL_FILE}"
+    /usr/bin/fakeroot /usr/bin/mksquashfs "${LOCAL_DIR}/${CODECS_BASE}" ${LOCAL_FILE} > /dev/null 2>&1
+    if /usr/bin/test $? -ne 0 ; then
+        cd "${HOME}"
+        /bin/rm -rf "${LOCAL_DIR}/${CODECS_BASE}"
+        /bin/rm -f ${LOCAL_FILE}
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to create the codecs file because squashfs failed."
+        /bin/false
+        return
+    fi
+
+    mm_conf_put "${REMOTE_FILE}" "${LOCAL_FILE}"
+    if /usr/bin/test $? -ne 0 ; then
+        cd "${HOME}"
+        /bin/rm -rf "${LOCAL_DIR}/${CODECS_BASE}"
+        /bin/rm -f ${LOCAL_FILE}
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to save the codecs file."
+        /bin/false
+        return
+    fi
+
+    cd "${HOME}"
+    /bin/rm -rf "${LOCAL_DIR}/${CODECS_BASE}"
+    /bin/rm -f "${LOCAL_FILE}"
+    /bin/true
+}
+
+mm_extras_save() {
+
+    if /usr/bin/test ! -d /usr/local ; then
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to create the extras file because the extras directory does not exist."
+        /bin/false
+        return
+    fi
+    if /usr/bin/test `ls -1 /usr/local | /usr/bin/wc -l` -eq 0 ; then
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to create the extras file because the extras directory is empty."
+        /bin/false
+        return
+    fi
+
+    local FILE
+    local REMOTE_FILE
+    local LOCAL_DIR
+    local LOCAL_FILE
+
+    FILE="extras.sfs"
+    REMOTE_FILE="${FILE}"
+    LOCAL_DIR="${HOME}/tmp"
+    LOCAL_FILE="${LOCAL_DIR}/${FILE}"
+
+    /bin/rm -f "${LOCAL_FILE}"
+    /bin/mkdir -p "${LOCAL_DIR}"
+    /usr/bin/mksquashfs /usr/local ${LOCAL_FILE} > /dev/null 2>&1
+    if /usr/bin/test $? -ne 0 ; then
+        /bin/rm -f ${LOCAL_FILE}
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to create the extras file because squashfs failed."
+        /bin/false
+        return
+    fi
+
+    mm_conf_put "${REMOTE_FILE}" "${LOCAL_FILE}"
+    if /usr/bin/test $? -ne 0 ; then
+        /bin/rm -f ${LOCAL_FILE}
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to save the extras file."
+        /bin/false
+        return
+    fi
+
+    /bin/rm -f "${LOCAL_FILE}"
+    /bin/true
+}
+
+mm_themecache_save() {
+
+    if /usr/bin/test ! -d /home/minimyth/.mythtv/themecache ; then
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to create the MythTV themecache file because the MythTV themecache directory does not exist."
+        /bin/false
+        return
+    fi
+    if /usr/bin/test ! "`cd /home/minimyth/.mythtv/themecache ; ls -1 | /bin/grep -c *`" = "1" ; then
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to create the MythTV themecache file because the MythTV themecache directory does not contain exactly one cached theme."
+        /bin/false
+        return
+    fi
+
+    local FILE
+    local REMOTE_FILE
+    local LOCAL_DIR
+    local LOCAL_FILE
+
+    FILE=`cd /home/minimyth/.mythtv/themecache ; ls`.sfs
+    REMOTE_FILE="themecaches/${FILE}"
+    LOCAL_DIR="${HOME}/tmp"
+    LOCAL_FILE="${LOCAL_DIR}/${FILE}"
+
+    /bin/rm -f "${LOCAL_FILE}"
+    /bin/mkdir -p "${LOCAL_DIR}"
+    /usr/bin/mksquashfs /home/minimyth/.mythtv/themecache ${LOCAL_FILE} > /dev/null 2>&1
+    if /usr/bin/test $? -ne 0 ; then
+        /bin/rm -f ${LOCAL_FILE}
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to create the MythTV themecache file because squashfs failed."
+        /bin/false
+        return
+    fi
+
+    mm_conf_put "${REMOTE_FILE}" "${LOCAL_FILE}"
+    if /usr/bin/test $? -ne 0 ; then
+        /bin/rm -f ${LOCAL_FILE}
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "failed to save the MythTV themecache file."
+        /bin/false
+        return
+    fi
+
+    /bin/rm -f "${LOCAL_FILE}"
+    /bin/true
 }
 
 mm_message_output() {
@@ -516,100 +720,6 @@ mm_var_get() {
     local VAR=$1
 
     /bin/echo `set | /bin/grep "^${VAR}=" | /bin/sed 's%^[^=]*=%%' | /bin/sed "s%^'%%" | /bin/sed "s%'$%%"`
-}
-
-#===============================================================================
-# squashfs functions
-#===============================================================================
-mm_squashfs_codecs_make() {
-
-    local FILE
-
-    if /usr/bin/test -d /usr/lib/codecs && /usr/bin/test `ls -1 /usr/lib/codecs | /usr/bin/wc -l` -ne 0 ; then
-        /bin/true
-    else
-        /bin/rm -rf /usr/lib/codecs
-        /bin/mkdir -p /usr/lib/codecs
-        cd /usr/lib/codecs
-        /usr/bin/wget http://www.mplayerhq.hu/MPlayer/releases/codecs/essential-20061022.tar.bz2
-        /bin/tar -jxf essential-20061022.tar.bz2
-        /bin/rm -f essential-20061022.tar.bz2
-        /bin/mv essential-20061022/* .
-        /bin/rm -rf essential-20061022
-    fi
-
-    FILE=/codecs.sfs
-    /usr/bin/mksquashfs /usr/lib/codecs ${FILE} > /dev/null 2>&1
-    if /usr/bin/test $? -ne 0 ; then
-        /bin/rm -f ${FILE}
-        /bin/echo "error: mksquashfs failed."
-        return 1
-    fi
-
-    /bin/chmod 644 ${FILE}
-
-    /bin/echo "created codecs squashfs image: \"${FILE}\"."
-    return 0
-}
-
-mm_squashfs_extras_make() {
-
-    local FILE
-    local INITRD_FILE
-    local INITRD_FILE_PREFIX
-
-    if /usr/bin/test ! -d /usr/local ; then
-        /bin/echo "error: the extras directory does not exist."
-        return 1
-    fi
-
-    INITRD_FILE=`/bin/echo ${initrd} | /bin/sed 's%^.*/%%'`
-    INITRD_FILE_PREFIX=`/bin/echo ${INITRD_FILE} | /bin/sed 's%-.*$%%'`
-    FILE=
-    if /usr/bin/test "${INITRD_FILE_PREFIX}" = "rootfs" ; then
-        FILE=/`/bin/echo ${INITRD_FILE} | /bin/sed 's%^rootfs%extras%'`.sfs
-    else
-        FILE=/extras.sfs
-    fi
-
-    /usr/bin/mksquashfs /usr/local ${FILE} > /dev/null 2>&1
-    if /usr/bin/test $? -ne 0 ; then
-        /bin/rm -f ${FILE}
-        /bin/echo "error: mksquashfs failed."
-        return 1
-    fi
-
-    /bin/chmod 644 ${FILE}
-
-    /bin/echo "created extras squashfs image: \"${FILE}\"."
-    return 0
-}
-
-mm_squashfs_themecache_make() {
-
-    local FILE
-
-    if /usr/bin/test ! -d /home/minimyth/.mythtv/themecache ; then
-        /bin/echo "error: the MythTV themecache directory does not exist."
-        return 1
-    fi
-    if /usr/bin/test ! "`cd /home/minimyth/.mythtv/themecache ; ls -1 | /bin/grep -c *`" = "1" ; then
-        /bin/echo "error: the MythTV themecache directory does not contain exactly one cached theme."
-        return 1
-    fi
-
-    FILE=/`cd /home/minimyth/.mythtv/themecache ; ls`.sfs
-    /usr/bin/mksquashfs /home/minimyth/.mythtv/themecache ${FILE} > /dev/null 2>&1
-    if /usr/bin/test $? -ne 0 ; then
-        /bin/rm -f ${FILE}
-        /bin/echo "error: mksquashfs failed."
-        return 1
-    fi
-
-    /bin/chmod 644 ${FILE}
-
-    /bin/echo "created themecache squashfs image: \"${FILE}\"."
-    return 0
 }
 
 #===============================================================================
