perforce changeset 852

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions
@@ -105,18 +105,19 @@ mm_uniq() {
 #             conf:themecache.tar.bz2
 #         The valid protocol values are: nfs, cifs, tftp, file and conf. For
 #         nfs and cifs the URL points to a remote directory. For tftp, the URL
-#         points to a tarfile (*.tar.bz2) or a cramfs image (*.cmg) on a TFTP
-#         server that will be downloaded and expanded into (for files) or
-#         downloaded and mounted at (for images) the mount point. For file, the
-#         URL point to a tarfile (*.tar.bz2), a cramfs image (*.cmg) or a 
-#         directory on the local file system that will be copied and expanded
-#         into (for files), copied and mounted at (for images) or mounted at
-#         (for directories) the mount point. For conf, the URL points to a
-#         tarfile (*.tar.bz2) or a cramfs image (*.cmg) in the MiniMyth conf
-#         directory that is either on the TFTP server (when network booting) or
-#         on the USB key (when USB booting) that will be downloaded/copied and
-#         expanded into (for files) or downloaded/copied and mounted at (for
-#         images) the mount point.
+#         points to a tarfile (*.tar.bz2), a cramfs image (*.cmg) or a squashfs
+#         image (*.sfs) on a TFTP server that will be downloaded and expanded
+#         into (for files) or downloaded and mounted at (for images) the mount
+#         point. For file, the URL point to a tarfile (*.tar.bz2), a cramfs
+#         image (*.cmg), a squashfs image (*.sfs) or a directory on the local
+#         file system that will be copied and expanded into (for files), copied
+#         and mounted at (for images) or mounted at (for directories) the mount
+#         point. For conf, the URL points to a tarfile (*.tar.bz2), a cramfs
+#         image (*.cmg) or squashfs image (*.sfs) in the MiniMyth conf directory
+#         that is either on the TFTP server (when network booting) or on the 
+#         local storage device (when IDE or USB booting) that will be
+#         downloaded/copied and expanded into (for files) or downloaded/copied
+#         and mounted at (for images) the mount point.
 #     MOUNT_DIR: required argument:
 #         The local directory (e.g. /mnt/music) where the URL will be mounted.
 #-------------------------------------------------------------------------------
@@ -159,7 +160,17 @@ mm_url_mount() {
             MOUNT_OPTIONS="${MOUNT_OPTIONS},password=${URL_PASSWORD}"
         fi
     elif [ "${URL_PROTOCOL}" = "tftp" ] ; then
-        if   [ "${URL_EXT1}" = "cmg" ] ; then
+        if   [ "${URL_EXT1}" = "sfs" ] ; then
+            DIR="/initrd/rw/loopfs/`echo ${MOUNT_DIR} | sed 's%//*%~%g'`"
+            FILE="image.sfs"
+            mkdir -p "${DIR}"
+            mkdir -p "${DIR}/ro"
+            mkdir -p "${DIR}/rw"
+            cd "${DIR}"
+            tftp -g -r "${URL_PATH}" -l "${FILE}" "${URL_SERVER}"
+            mount -t squashfs -o loop "${DIR}/${FILE}" "${DIR}/ro"
+            mount -t unionfs -o dirs=${DIR}/rw=rw:${DIR}/ro=ro none "${MOUNT_DIR}"
+        elif [ "${URL_EXT1}" = "cmg" ] ; then
             DIR="/initrd/rw/loopfs/`echo ${MOUNT_DIR} | sed 's%//*%~%g'`"
             FILE="image.cmg"
             mkdir -p "${DIR}"
@@ -177,7 +188,17 @@ mm_url_mount() {
             rm -f "${TARFILE}"
         fi
     elif [ "${URL_PROTOCOL}" = "conf" ] ; then
-        if   [ "${URL_EXT1}" = "cmg" ] ; then
+        if   [ "${URL_EXT1}" = "sfs" ] ; then
+            DIR="/initrd/rw/loopfs/`echo ${MOUNT_DIR} | sed 's%//*%~%g'`"
+            FILE="image.sfs"
+            mkdir -p "${DIR}"
+            mkdir -p "${DIR}/ro"
+            mkdir -p "${DIR}/rw"
+            cd "${DIR}"
+            mm_conf_get "${URL_PATH}" "${FILE}"
+            mount -t squashfs -o loop "${DIR}/${FILE}" "${DIR}/ro"
+            mount -t unionfs -o dirs=${DIR}/rw=rw:${DIR}/ro=ro none "${MOUNT_DIR}"
+        elif [ "${URL_EXT1}" = "cmg" ] ; then
             DIR="/initrd/rw/loopfs/`echo ${MOUNT_DIR} | sed 's%//*%~%g'`"
             FILE="image.cmg"
             mkdir -p "${DIR}"
@@ -196,7 +217,17 @@ mm_url_mount() {
         fi
     elif [ "${URL_PROTOCOL}" = "file" ] ; then
         if   [ -f "${URL_PATH}" ] ; then
-            if   [ "${URL_EXT1}" = "cmg" ] ; then
+            if   [ "${URL_EXT1}" = "sfs" ] ; then
+                DIR="/initrd/rw/loopfs/`echo ${MOUNT_DIR} | sed 's%//*%~%g'`"
+                FILE="image.sfs"
+                mkdir -p "${DIR}"
+                mkdir -p "${DIR}/ro"
+                mkdir -p "${DIR}/rw"
+                cd "${DIR}"
+                cp "${URL_PATH}" "${FILE}"
+                mount -t squashfs -o loop "${DIR}/${FILE}" "${DIR}/ro"
+                mount -t unionfs -o dirs=${DIR}/rw=rw:${DIR}/ro=ro none "${MOUNT_DIR}"
+            elif [ "${URL_EXT1}" = "cmg" ] ; then
                 DIR="/initrd/rw/loopfs/`echo ${MOUNT_DIR} | sed 's%//*%~%g'`"
                 FILE="image.cmg"
                 mkdir -p "${DIR}"
@@ -241,6 +272,30 @@ mm_var_get() {
     VAR=$1
 
     echo `set | grep "^${VAR}=" | sed 's%^[^=]*=%%' | sed "s%^'%%" | sed "s%'$%%"`
+}
+
+mm_themecache_squashfs_make() {
+    if [ ! -d /root/.mythtv/themecache ] ; then
+        echo "error: the MythTV themecache directory does not exist."
+        return 1
+    fi
+    if [ ! "`cd /root/.mythtv/themecache ; ls -1 | grep -c *`" = "1" ] ; then
+        echo "error: the MythTV themecache directory does not contain exactly one cached theme."
+        return 1
+    fi
+
+    FILE=`cd /root/.mythtv/themecache ; ls`.sfs
+    mksquashfs /root/.mythtv/themecache /${FILE} > /dev/null 2>&1
+    if [ ! "$?" = "0" ] ; then
+        rm -f /${FILE}
+        echo "error: mksquashfs failed."
+        return 1
+    fi
+
+    chmod 644 /${FILE}
+
+    echo "created themecache squashfs image: \"/${FILE}\"."
+    return 0
 }
 
 #===============================================================================
diff --git a/trunk/gar-minimyth/script/meta/minimyth/files/mkflashboot b/trunk/gar-minimyth/script/meta/minimyth/files/mkflashboot
--- a/trunk/gar-minimyth/script/meta/minimyth/files/mkflashboot
+++ b/trunk/gar-minimyth/script/meta/minimyth/files/mkflashboot
@@ -1,13 +1,14 @@
 #!/bin/sh 
 #
-# This script creates a USB key that boots MiniMyth.
+# This script installs the files needed to make a flash device boot MiniMyth.
 
-volume_path=/tmp/mkusbkey
+volume_path=/tmp/mkflashboot
 
-distro_path=$1
-conf_path=$2
-version=$3
-device=$4
+boot_type=$1
+distro_path=$2
+conf_path=$3
+version=$4
+device=$5
 
 kernel=
 rootfs=
@@ -45,7 +46,6 @@ if [ ! "$?" = "0" ] ; then
 fi
 
 if [ -z "${conf_path}" ] ; then
-    conf_path="${distro_path}"
     if [ -d ${distro_path}/conf ] ; then
         conf_path=${distro_path}
     fi
@@ -110,18 +110,24 @@ if [ -z "${device}" ] ; then
     fi
 fi
 
-if [ -z "${distro_path}" ] || [ -z "${conf_path}" ] || [ -z "${version}" ] || [ -z "${device}" ] ; then
+if [ -z "${boot_type}" ] || [ -z "${distro_path}" ] || [ -z "${conf_path}" ] || [ -z "${version}" ] || [ -z "${device}" ] ; then
     echo "usage:"
-    echo "    $0 <distro_path> [ <conf_path> [ <version> [ <device> ] ] ]"
+    echo "    $0 <type> <distro_path> [ <conf_path> [ <version> [ <device> ] ] ]"
     echo "where:"
+    echo "    <boot_type>  : MM_BOOT_TYPE. Valid values are 'ide' or 'usb'."
     echo "    <distro_path>: Path to the location of the MiniMyth kernel and rootfs."
     echo "    <conf_path>  : Path to the location of the MiniMyth conf directory."
     echo "                   Default is <distro_path>."
     echo "    <version>    : MiniMyth version."
     echo "                   Default is newest kernel, rootfs and extras in <distro_path>."
-    echo "    <device>     : usb key (e.g. sda)."
+    echo "    <device>     : flash device (e.g. sda)."
     echo "example:"
     echo "    $0 /var/tftpboot/minimyth"
+    exit 1
+fi
+
+if [ ! "${boot_type}" == "ide" ] && [ ! "${boot_type}" == "usb" ] ; then
+    echo "error: <boot_type> is \'${boot_type}\' but must be either 'ide' or 'usb'."
     exit 1
 fi
 
@@ -141,29 +147,29 @@ if [ ! -f /sys/block/${device}/removable ] ; then
 fi
 
 if [ ! "`cat /sys/block/${device}/removable`" = "1" ] ; then
-    echo "error: ${device} is not a usb key because it is not removable."
+    echo "error: ${device} is not a flash device because it is not removable."
     exit 1
 fi
 
 if [ ! -f /sys/block/${device}/device/vendor ] ; then
-    echo "error: cannot determine usb key vendor."
+    echo "error: cannot determine flash device vendor."
     exit 1
 fi
 
 if [ ! -f /sys/block/${device}/device/model ] ; then
-    echo "error: cannot determine usb key model."
+    echo "error: cannot determine flash device model."
     exit 1
 fi
 
 vendor=`cat /sys/block/${device}/device/vendor | sed 's%^ *%%g'`
 model=`cat /sys/block/${device}/device/model   | sed 's% *$%%g'`
 
-echo "Making a bootable USB based on the following information:"
-echo "    usb key: /dev/${device} (vendor: '${vendor}', model: '${model}')"
-echo "    kernel:  ${kernel}"
-echo "    rootfs:  ${rootfs}"
-echo "    extras:  ${extras}"
-echo "    conf:    ${conf_path}/conf"
+echo "Making a bootable flash device based on the following information:"
+echo "    flash device: /dev/${device} (vendor: '${vendor}', model: '${model}')"
+echo "    kernel:       ${kernel}"
+echo "    rootfs:       ${rootfs}"
+echo "    extras:       ${extras}"
+echo "    conf:         ${conf_path}/conf"
 echo -n "Continue [y/N]? "
 read response
 if [ -z "${response}" ] ; then
@@ -178,15 +184,15 @@ rm -rf   ${volume_path}
 mkdir -p ${volume_path}
 
 mkdir -p ${volume_path}/stage
-echo "DEFAULT minimyth"                                                                                       \
+echo "DEFAULT minimyth"                                                                                                \
 	>> ${volume_path}/stage/syslinux.cfg
-echo ""                                                                                                       \
+echo ""                                                                                                                \
 	>> ${volume_path}/stage/syslinux.cfg
-echo "LABEL minimyth"                                                                                         \
+echo "LABEL minimyth"                                                                                                  \
 	>> ${volume_path}/stage/syslinux.cfg
-echo "	KERNEL kernel"                                                                                        \
+echo "	KERNEL kernel"                                                                                                 \
 	>> ${volume_path}/stage/syslinux.cfg
-echo "	APPEND ro root=/dev/ram0 initrd=rootfs ramdisk_blocksize=4096 ramdisk=64000 irqpoll MM_BOOT_TYPE=usb" \
+echo "	APPEND ro root=/dev/ram0 initrd=rootfs ramdisk_blocksize=4096 ramdisk=64000 irqpoll MM_BOOT_TYPE=${boot_type}" \
 	>> ${volume_path}/stage/syslinux.cfg
 if [ -e ${kernel}         ] ; then
     cp -r ${kernel}         ${volume_path}/stage/kernel
