- Made LIRC sleep/wake more robust by trying to put the frontend in a more stable state before sleep.

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/functions
@@ -1004,6 +1004,16 @@ mm_mythdb_jumppoints_update() {
         WHERE hostname=\"${HOSTNAME}\" AND destination=\"${DESTINATION}\""
 }
 
+mm_mythdb_jumppoints_get() {
+    local VALUE=$1
+
+    local DATA
+
+    DATA=`mm_mythdb_jumppoints_dump "$1" | /bin/grep -e "$1" |  /usr/bin/cut -f 3`
+
+    /bin/echo "${DATA}"
+}
+
 mm_mythdb_keybindings_delete() {
     local CONTEXT=$1
     local ACTION=$2
@@ -1477,4 +1487,44 @@ mm_hardware_motherboard2kernel_map() {
     /usr/bin/logger -t minimyth -p "local0.warn" "    motherboard vendor='${vendor}', product='${product}' unknown."
     /usr/bin/logger -t minimyth -p "local0.warn" "    some kernel modules may not be loaded."
     return 0
+}
+
+#===============================================================================
+# xmacro functions.
+#===============================================================================
+mm_xmacroplay() {
+    program="$1"
+    command="$2"
+
+    # Make sure that the program is running.
+    if /usr/bin/test -n "`/bin/pidof ${program}`" ; then
+        # Make sure that the X window manager is running, since we depend on it to select the program window.
+        if /usr/bin/test -n "`/bin/pidof ratpoison`" ; then
+            # Set ratpoison to select window by program name.
+            /usr/bin/ratpoison -d :0.0 -c "set winname class"
+            # Select the program window.
+            /usr/bin/ratpoison -d :0.0 -c "select ${program}"
+            # Make sure the program window is selected. 
+            window=`/usr/bin/ratpoison -d :0.0 -c "info" 2> /dev/null | /bin/sed -e 's%^.*(\([^()]*\))$%\1%'`
+            /bin/echo "${window}" | /bin/grep -q -i "${program}" 2> /dev/null
+            if /usr/bin/test $? -eq 0 ; then
+                # Send exit key sequence to window.
+                /bin/echo -e "${command}" | /usr/bin/xmacroplay -d 100 :0.0 > /dev/null 2>&1
+            fi
+        else
+            mm_message_output error "cannot command '${program}' without X window manager enabled."
+        fi
+    fi
+}
+
+mm_xmacroplay_exit_program() {
+    program="$1"
+    command="$2"
+
+    if /usr/bin/test -n "`/bin/pidof ${program}`" ; then
+        mm_xmacroplay "${program}" "${command}"
+        if /usr/bin/test -n "`/bin/pidof ${program}`" ; then
+            mm_message_output error "failed to exit '${program}'."
+        fi
+    fi
 }
