- Fixed init so that MM_MEDIA_TV_URL does not need to be writable by   user 'minimyth' unless mythbackend is enabled (MM_BACKEND_ENABLED='yes'),   but is must still be readable by user 'minimyth'.

diff --git a/trunk/gar-minimyth/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/media b/trunk/gar-minimyth/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/media
--- a/trunk/gar-minimyth/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/media
+++ b/trunk/gar-minimyth/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/media
@@ -19,9 +19,11 @@ start() {
             mm_message_output err "error: '${MM_MEDIA_TV_MOUNTPOINT}' is not readable by user 'minimyth'."
             exit 1
         fi
-        if /bin/su -c "/usr/bin/test ! -w ${MM_MEDIA_TV_MOUNTPOINT}"      - minimyth ; then
-            mm_message_output err "error: '${MM_MEDIA_TV_MOUNTPOINT}' is not writable by user 'minimyth'."
-            exit 1
+        if /usr/bin/test "${MM_BACKEND_ENABLED}" = "yes" ; then
+            if /bin/su -c "/usr/bin/test ! -w ${MM_MEDIA_TV_MOUNTPOINT}" - minimyth ; then
+                mm_message_output err "error: '${MM_MEDIA_TV_MOUNTPOINT}' is not writable by user 'minimyth'."
+                exit 1
+            fi
         fi
     fi
     if /usr/bin/test -n "${MM_MEDIA_GALLERY_URL}" && /usr/bin/test -n "${MM_MEDIA_GALLERY_MOUNTPOINT}" ; then
