Changed init scripts so that they treat minimyth.conf as a shell script. Added MM_CONF_VERSION. Changed MM_MYTHDB_* to MM_MYTHDB_*_{key}.

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf.d/mythdb b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf.d/mythdb
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf.d/mythdb
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf.d/mythdb
@@ -7,19 +7,31 @@ conf_clean_mythdb() {
 
 conf_check_mythdb() {
     # Check for obsolete variables.
-    if /usr/bin/test ! -z "${MM_MYTHDB_JUMPOINT}"   ; then
+    if /usr/bin/test ! -z "${MM_MYTHDB_JUMPOINT}"    ; then
         mm_message_output err 'error: "minimyth.conf" is out of date. "MM_MYTHDB_JUMPPOINT" is obsolete.'
         exit 1
     fi
-    if /usr/bin/test ! -z "${MM_MYTHDB_KEYBINDING}" ; then
+    if /usr/bin/test ! -z "${MM_MYTHDB_JUMPOINTS}"   ; then
+        mm_message_output err 'error: "minimyth.conf" is out of date. "MM_MYTHDB_JUMPPOINTS" is obsolete.'
+        exit 1
+    fi
+    if /usr/bin/test ! -z "${MM_MYTHDB_KEYBINDING}"  ; then
         mm_message_output err 'error: "minimyth.conf" is out of date. "MM_MYTHDB_KEYBINDING" is obsolete.'
         exit 1
     fi
-    if /usr/bin/test ! -z "${MM_MYTHDB_SETTING}"    ; then
+    if /usr/bin/test ! -z "${MM_MYTHDB_KEYBINDINGS}" ; then
+        mm_message_output err 'error: "minimyth.conf" is out of date. "MM_MYTHDB_KEYBINDINGS" is obsolete.'
+        exit 1
+    fi
+    if /usr/bin/test ! -z "${MM_MYTHDB_SETTING}"     ; then
         mm_message_output err 'error: "minimyth.conf" is out of date. "MM_MYTHDB_SETTING" is obsolete.'
         exit 1
     fi
-    if /bin/cat /etc/minimyth.d/minimyth.conf | /bin/grep -q '^MM_MYTHDB_SETTING_' ; then
+    if /usr/bin/test ! -z "${MM_MYTHDB_SETTINGS}"    ; then
+        mm_message_output err 'error: "minimyth.conf" is out of date. "MM_MYTHDB_SETTINGS" is obsolete.'
+        exit 1
+    fi
+    if set | /bin/grep -q '^MM_MYTHDB_SETTING_'      ; then
         mm_message_output err 'error: "minimyth.conf" is out of date. "MM_MYTHDB_SETTING_<setting>" is obsolete.'
         exit 1
     fi
@@ -33,6 +45,25 @@ conf_default_mythdb() {
 
 conf_write_mythdb() {
     local conf_file=$1
+
+    set | /bin/grep -e '^MM_MYTHDB_JUMPPOINTS_[^=]*=' | \
+    while read variable ; do
+        variable_name=`/bin/echo ${variable} | /bin/sed -e "s%\([^=]*\)='\(.*\)'$%\1%"`
+        variable_value=`/bin/echo ${variable} | /bin/sed -e "s%\([^=]*\)='\(.*\)'$%\2%"`
+        conf_variable_write "${conf_file}" "${variable_name}" "${variable_value}"
+    done
+    set | /bin/grep -e '^MM_MYTHDB_KEYBINDINGS_[^=]*=' | \
+    while read variable ; do
+        variable_name=`/bin/echo ${variable} | /bin/sed -e "s%\([^=]*\)='\(.*\)'$%\1%"`
+        variable_value=`/bin/echo ${variable} | /bin/sed -e "s%\([^=]*\)='\(.*\)'$%\2%"`
+        conf_variable_write "${conf_file}" "${variable_name}" "${variable_value}"
+    done
+    set | /bin/grep -e '^MM_MYTHDB_SETTINGS_[^=]*=' | \
+    while read variable ; do
+        variable_name=`/bin/echo ${variable} | /bin/sed -e "s%\([^=]*\)='\(.*\)'$%\1%"`
+        variable_value=`/bin/echo ${variable} | /bin/sed -e "s%\([^=]*\)='\(.*\)'$%\2%"`
+        conf_variable_write "${conf_file}" "${variable_name}" "${variable_value}"
+    done
 
     return 0
 }
