perforce changeset 914

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf.d/x b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf.d/x
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf.d/x
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf.d/x
@@ -37,6 +37,9 @@ conf_check_x() {
         exit 1
     fi
 
+    # Reset the variables.
+    conf_reset 'MM_X_'
+
     # Check X application variables.
     if /usr/bin/test ! -z "${MM_X_WM_ENABLED}"          && \
        /usr/bin/test !    "${MM_X_WM_ENABLED}" = "yes"  && \
@@ -122,7 +125,7 @@ conf_check_x() {
     fi
     # Check the format of MM_X_MODELINE.
     if /usr/bin/test -n "${MM_X_MODELINE}" ; then
-        /bin/echo ${MM_X_MODELINE} | /bin/grep -q -e '^Modeline "[0-9][0-9]*x[0-9][^"]*".*' > /dev/null 2>&1
+        /bin/echo ${MM_X_MODELINE} | /bin/grep -q -e '^[Mm][Oo][Dd][Ee][Ll][Ii][Nn][Ee]  *"[0-9][0-9]*[Xx][0-9][^"]*".*' > /dev/null 2>&1
         if /usr/bin/test $? -ne 0 ; then
             mm_message_output err 'error: 'MM_X_MODELINE' format is not valid'
             exit 1
@@ -130,7 +133,7 @@ conf_check_x() {
     fi
     # Check the format of MM_X_MODE.
     if /usr/bin/test -n "${MM_X_MODE}" ; then
-        /bin/echo ${MM_X_MODE} | /bin/grep -q -e '^[0-9][0-9]*x[0-9][0-9]*' > /dev/null 2>&1
+        /bin/echo ${MM_X_MODE} | /bin/grep -q -e '^[0-9][0-9]*[Xx][0-9].*' > /dev/null 2>&1
         if /usr/bin/test $? -ne 0 ; then
             mm_message_output err 'error: 'MM_X_MODE' format is not valid'
             exit 1
@@ -149,6 +152,9 @@ conf_default_x() {
 
     # The routine relies on MM_VIDEO_* variables.
     conf_default_video
+
+    # Reset the variables.
+    conf_reset 'MM_X_'
 
     # X driver variables.
     if /usr/bin/test -z "${MM_X_DRIVER}"              ; then
@@ -223,12 +229,12 @@ conf_default_x() {
 
     # Auto-configure MM_X_MODE based on MM_X_MODELINE.
     if /usr/bin/test -n "${MM_X_MODELINE}" ; then
-        /bin/echo ${MM_X_MODELINE} | /bin/grep -q -e '^Modeline "[0-9][0-9]*x[0-9][^"]*".*' > /dev/null 2>&1
+        /bin/echo ${MM_X_MODELINE} | /bin/grep -q -e '^[Mm][Oo][Dd][Ee][Ll][Ii][Nn][Ee]  *"[0-9][0-9]*[Xx][0-9][^"]*".*' > /dev/null 2>&1
         if /usr/bin/test $? -ne 0 ; then
             mm_message_output err 'error: 'MM_X_MODELINE' format is not valid'
             exit 1
         fi
-        MM_X_MODE=`/bin/echo ${MM_X_MODELINE} | /bin/sed 's%^Modeline "\([0-9][0-9]*x[0-9][^"]*\)".*%\1%'`
+        MM_X_MODE=`/bin/echo ${MM_X_MODELINE} | /bin/sed 's%^[Mm][Oo][Dd][Ee][Ll][Ii][Nn][Ee]  *"\([0-9][0-9]*[Xx][0-9][^"]*\)".*%\1%'`
     fi
 
     # Auto-configure MM_X_MODE.
@@ -264,15 +270,25 @@ conf_default_x() {
         esac
     fi
 
-    # Auto-configure MM_X_DISPLAYSIZE.
-    if /usr/bin/test -z "${MM_X_DISPLAYSIZE}"         || /usr/bin/test "${MM_X_DISPLAYSIZE}"         = "auto" ; then
-        /bin/echo ${MM_X_MODE} | /bin/grep -q -e '^[0-9][0-9]*x[0-9][0-9]*' > /dev/null 2>&1
+    # Auto-configure MM_X_RESOLUTION based on MM_X_MODE.
+    if /usr/bin/test -z "${MM_X_RESOLUTION}" ; then
+        /bin/echo ${MM_X_MODE} | /bin/grep -q -e '^[0-9][0-9]*[Xx][0-9].*' > /dev/null 2>&1
         if /usr/bin/test $? -ne 0 ; then
             mm_message_output err 'error: 'MM_X_MODE' format is not valid'
             exit 1
         fi
-        X_RESOLUTION_X=`/bin/echo ${MM_X_MODE} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\).*%\1%'`
-        X_RESOLUTION_Y=`/bin/echo ${MM_X_MODE} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\).*%\2%'`
+        MM_X_RESOLUTION=`/bin/echo ${MM_X_MODE} | /bin/sed -e 's%^\([0-9][0-9]*\)[Xx]\([0-9][0-9]*\).*%\1x\2%'`
+    fi
+
+    # Auto-configure MM_X_DISPLAYSIZE based on MM_X_RESOLUTION.
+    if /usr/bin/test -z "${MM_X_DISPLAYSIZE}"         || /usr/bin/test "${MM_X_DISPLAYSIZE}"         = "auto" ; then
+        /bin/echo ${MM_X_RESOLUTION} | /bin/grep -q -e '^[0-9][0-9]*x[0-9][0-9]*' > /dev/null 2>&1
+        if /usr/bin/test $? -ne 0 ; then
+            mm_message_output err 'error: 'MM_X_RESOLUTION' format is not valid'
+            exit 1
+        fi
+        X_RESOLUTION_X=`/bin/echo ${MM_X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\1%'`
+        X_RESOLUTION_Y=`/bin/echo ${MM_X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\2%'`
         # MythTV is reported to work best at 100dots/inch.
         # (100dots/inch) / (25.4inch/mm) ~ 4dots/mm
         # Y in mm = (Y in dots) / (4dots/mm)
