- Changed mm_message_output to write to file '/var/log/minimyth.*.log' as well. - Change conf processes to fail only after all conf process is done so that   the user can get all of the conf errors in one pass.

diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf
@@ -85,6 +85,13 @@ start() {
         conf_clean_${file}
     done
 
+    # If there are any errors, then do not continue
+    if /usr/bin/test -e /var/log/minimyth.err.log &&
+       /usr/bin/test `/bin/cat /var/log/minimyth.err.log | /usr/bin/wc -l` -gt 0 ; then
+        mm_message_output err "error: check '/var/log/minimyth.err.log' for details."
+        exit 1
+    fi
+
     return 0
 }
 
diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/network b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/network
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/network
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/network
@@ -21,6 +21,15 @@ start() {
     else
         /sbin/udhcpc -s /etc/udhcpc.script -i eth0 -r $ip  >> /dev/null 2>&1
     fi
+    if /usr/bin/test $? -ne 0 ; then
+        mm_message_output err "error: DHCP failed."
+        exit 1
+    fi
+    ip=`/sbin/ifconfig eth0 | /bin/grep '^ *inet addr:' | /bin/sed 's%^ *inet addr:\([^ ]*\) .*%\1%'`
+    if /usr/bin/test -z "$ip" ; then
+        mm_message_output err "error: DHCP failed."
+        exit 1
+    fi
 
     # Start portmap on local interface.
     /sbin/portmap -l
