perforce changeset 885

diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf
@@ -15,6 +15,10 @@ conf_check() {
         mm_message_output err 'error: "minimyth.conf" is out of date. "MM_CODECS_URL=default" is obsolete.'
         exit 1
     fi
+    if /usr/bin/test "${MM_EXTRAS_URL}"         = "default"        ; then
+        mm_message_output err 'error: "minimyth.conf" is out of date. "MM_EXTRAS_URL=default" is obsolete.'
+        exit 1
+    fi
     if /usr/bin/test "${MM_LIRC_DRIVER}"        = "mceusbnew"      ; then
         mm_message_output err 'error: "minimyth.conf" is out of date. "MM_LIRC_DRIVER=mceusbnew" is obsolete.'
         exit 1
@@ -317,7 +321,6 @@ start() {
         exit 1
     fi
 
-    core_check
     conf_check
 
     conf_init
diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/mythtv b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/mythtv
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/mythtv
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/mythtv
@@ -9,6 +9,16 @@
 start() {
     mm_message_output info 'configuring MythTV ...'
 
+    # Check for required variables.
+    if /usr/bin/test -z "${MM_THEME_NAME}"    ; then
+        mm_message_output err 'error: "MM_THEME_NAME" not present.'
+        exit 1
+    fi
+    if /usr/bin/test -z "${MM_THEMEOSD_NAME}" ; then
+        mm_message_output err 'error: "MM_THEMEOSD_NAME" not present.'
+        exit 1
+    fi
+
     # Set OSD fonts.
     mm_mythdb_setting_update "OSDFont"   "luxisr.ttf"
     mm_mythdb_setting_update "OSDCCFont" "luxisr.ttf"
@@ -21,35 +31,55 @@ start() {
         mm_mythdb_setting_update "OSDTheme" "${MM_THEMEOSD_NAME}"
     fi
 
-    # Mount theme directory.
+    # Mount user specified theme directories.
     if /usr/bin/test -n "${MM_THEME_URL}" ; then
-        if /usr/bin/test ! -n "${MM_THEME_NAME}" ; then
-            mm_message_output err 'error: "MM_THEME_NAME" not present.'
-            exit 1
-        fi
         if /usr/bin/test -e "/usr/share/themes/${MM_THEME_NAME}" ; then
-            mm_message_output err "error: theme directory \"${MM_THEME_NAME}\" already exists."
+            mm_message_output err "error: MythTV theme directory '${MM_THEME_NAME}' already exists."
             exit 1
         fi
         mm_url_mount "${MM_THEME_URL}" "/usr/share/mythtv/themes/${MM_THEME_NAME}"
-    fi
-
-    # Mount OSD theme directory.
-    if /usr/bin/test -n "${MM_THEMEOSD_URL}" ; then
-        if /usr/bin/test ! -n "${MM_THEMEOSD_NAME}" ; then
-            mm_message_output err 'error: "MM_THEMEOSD_NAME" not present.'
+        if /usr/bin/test $? -ne 0 ; then
+            mm_message_output err "error: mount of 'MM_THEME_URL=${MM_THEME_URL}'' failed."
             exit 1
         fi
+    fi
+    if /usr/bin/test -n "${MM_THEMEOSD_URL}" ; then
         if /usr/bin/test -e "/usr/share/themes/${MM_THEMEOSD_NAME}" ; then
-            mm_message_output err "error: theme directory \"${MM_THEMEOSD_NAME}\" already exists."
+            mm_message_output err "error: MythTV OSD theme directory '${MM_THEMEOSD_NAME}' already exists."
             exit 1
         fi
         mm_url_mount "${MM_THEMEOSD_URL}" "/usr/share/mythtv/themes/${MM_THEMEOSD_NAME}"
+        if /usr/bin/test $? -ne 0 ; then
+            mm_message_output err "error: mount of 'MM_THEMEOSD_URL=${MM_THEMEOSD_URL}' failed."
+            exit 1
+        fi
+    fi
+
+    # Mount distribution provided theme directories.
+    if /usr/bin/test ! -e "/usr/share/themes/${MM_THEME_NAME}"    ; then
+        mm_url_mount "dist:themes/${MM_THEME_NAME}.sfs"    "/usr/share/mythtv/themes/${MM_THEME_NAME}"
+    fi
+    if /usr/bin/test ! -e "/usr/share/themes/${MM_OSDTHEME_NAME}" ; then
+        mm_url_mount "dist:themes/${MM_THEMEOSD_NAME}.sfs" "/usr/share/mythtv/themes/${MM_THEMEOSD_NAME}"
+    fi
+
+    # Check for theme directories.
+    if /usr/bin/test ! -e "/usr/share/mythtv/themes/${MM_THEME_NAME}"    ; then
+        mm_message_output err "error: MythTV theme '${MM_THEME_NAME}' not found."
+        exit 1
+    fi
+    if /usr/bin/test ! -e "/usr/share/mythtv/themes/${MM_THEMEOSD_NAME}" ; then
+        mm_message_output err "error: MythTV OSD theme '${MM_THEMEOSD_NAME}' not found."
+        exit 1
     fi
 
     # Mount themecache directory.
     if /usr/bin/test -n "${MM_THEMECACHE_URL}" ; then
         mm_url_mount "${MM_THEMECACHE_URL}" "/root/.mythtv/themecache"
+        if /usr/bin/test $? -ne 0 ; then
+            mm_message_output err "error: mount of 'MM_THEMECACHE_URL=${MM_THEMECACHE_URL}' failed."
+            exit 1
+        fi
     fi
 
     # Configure MythDVD ripping.
