perforce changeset 680

diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/conf
@@ -6,26 +6,38 @@
 ################################################################################
 . /etc/rc.d/functions
 
-conf_file=/etc/conf.d/minimyth
-
-conf_variable_write() {
-    echo -n "$1="  >> ${conf_file}
-    echo -n "'"    >> ${conf_file}
-    echo -n "$2"   >> ${conf_file}
-    echo    "'"    >> ${conf_file}
+# Check core (/etc/conf.d/core) configuration file.
+core_check() {
+    # Read DHCP configuration file file.
+    [ -r /etc/conf.d/core ] && . /etc/conf.d/core
 
     return 0
 }
 
-conf_init() {
-    rm -rf ${conf_file}
+# Check dhcp (/etc/conf.d/dhcp) configuration file.
+dhcp_check() {
+    # Read DHCP configuration file file.
+    [ -r /etc/conf.d/dhcp ] && . /etc/conf.d/dhcp
+
+    if [ -z "${MM_HOSTNAME}"   ] ; then
+        mm_message_output err 'error: no hostname provided by DHCP.'
+        exit 1
+    fi
+    if [ -z "${MM_DNS_SERVER}" ] ; then
+        mm_message_output err 'error: no DNS server provided by DHCP.'
+        exit 1
+    fi
+    if [ -z "${MM_NTP_SERVER}" ] ; then
+        mm_message_output err 'error: no NTP server provided by DHCP.'
+        exit 1
+    fi
 
     return 0
 }
 
 # Check minimyth.conf for obosolete variables and values.
 conf_check() {
-    # Read MiniMyth environment variables from the MiniMyth configuration file.
+    # MiniMyth configuration file.
     [ -r /etc/minimyth.d/minimyth.conf ] && . /etc/minimyth.d/minimyth.conf
     
     if [ "${MM_CODECS_URL}"         = "default"        ] ; then
@@ -93,12 +105,29 @@ conf_check() {
     return 0
 }
 
+conf_file=/etc/conf.d/minimyth
+
+conf_variable_write() {
+    echo -n "$2="  >> $1
+    echo -n "'"    >> $1
+    echo -n "$3"   >> $1
+    echo    "'"    >> $1
+
+    return 0
+}
+
+conf_init() {
+    rm -rf ${conf_file}
+
+    return 0
+}
+
 conf_write() {
     # Read MiniMyth environment variables from the MiniMyth configuration file.
     [ -r /etc/minimyth.d/minimyth.conf ] && . /etc/minimyth.d/minimyth.conf
     
     # Timezone.
-    conf_variable_write MM_TZ "${MM_TZ}"
+    conf_variable_write "${conf_file}" MM_TZ "${MM_TZ}"
 
     # Hardware.
     [ -z "${MM_HARDWARE_MOTHERBOARD}" ] && MM_HARDWARE_MOTHERBOARD="VIA_EPIA_M"
@@ -196,29 +225,29 @@ conf_write() {
             MM_HARDWARE_CPU="C3"
             ;;
     esac
-    conf_variable_write MM_HARDWARE_CHIPSET     "${MM_HARDWARE_CHIPSET}"
-    conf_variable_write MM_HARDWARE_MOTHERBOARD "${MM_HARDWARE_MOTHERBOARD}"
-    conf_variable_write MM_HARDWARE_NORTHBRIDGE "${MM_HARDWARE_NORTHBRIDGE}"
-    conf_variable_write MM_HARDWARE_SOUTHBRIDGE "${MM_HARDWARE_SOUTHBRIDGE}"
-    conf_variable_write MM_HARDWARE_LAN         "${MM_HARDWARE_LAN}"
-    conf_variable_write MM_HARDWARE_AUDIO       "${MM_HARDWARE_AUDIO}"
-    conf_variable_write MM_HARDWARE_TV          "${MM_HARDWARE_TV}"
-    conf_variable_write MM_HARDWARE_SENSOR      "${MM_HARDWARE_SENSOR}"
-    conf_variable_write MM_HARDWARE_CPU         "${MM_HARDWARE_CPU}"
+    conf_variable_write "${conf_file}" MM_HARDWARE_CHIPSET     "${MM_HARDWARE_CHIPSET}"
+    conf_variable_write "${conf_file}" MM_HARDWARE_MOTHERBOARD "${MM_HARDWARE_MOTHERBOARD}"
+    conf_variable_write "${conf_file}" MM_HARDWARE_NORTHBRIDGE "${MM_HARDWARE_NORTHBRIDGE}"
+    conf_variable_write "${conf_file}" MM_HARDWARE_SOUTHBRIDGE "${MM_HARDWARE_SOUTHBRIDGE}"
+    conf_variable_write "${conf_file}" MM_HARDWARE_LAN         "${MM_HARDWARE_LAN}"
+    conf_variable_write "${conf_file}" MM_HARDWARE_AUDIO       "${MM_HARDWARE_AUDIO}"
+    conf_variable_write "${conf_file}" MM_HARDWARE_TV          "${MM_HARDWARE_TV}"
+    conf_variable_write "${conf_file}" MM_HARDWARE_SENSOR      "${MM_HARDWARE_SENSOR}"
+    conf_variable_write "${conf_file}" MM_HARDWARE_CPU         "${MM_HARDWARE_CPU}"
 
     # CPU frequency governor.
     [ -z "${MM_CPUFREQ_GOVERNOR}" ] && MM_CPUFREQ_GOVERNOR="performance"
-    conf_variable_write MM_CPUFREQ_GOVERNOR "${MM_CPUFREQ_GOVERNOR}"
+    conf_variable_write "${conf_file}" MM_CPUFREQ_GOVERNOR "${MM_CPUFREQ_GOVERNOR}"
 
     # Audio.
     [ -z "${MM_AUDIO_TYPE}" ] && MM_AUDIO_TYPE="analog"
-    conf_variable_write MM_AUDIO_TYPE "${MM_AUDIO_TYPE}"
+    conf_variable_write "${conf_file}" MM_AUDIO_TYPE "${MM_AUDIO_TYPE}"
 
     # Video.
     [ -z "${MM_VIDEO_ASPECT_RATIO}"        ] && MM_VIDEO_ASPECT_RATIO="4:3"
     [ -z "${MM_VIDEO_DEINTERLACE_ENABLED}" ] && MM_VIDEO_DEINTERLACE_ENABLED="no"
-    conf_variable_write MM_VIDEO_ASPECT_RATIO        "${MM_VIDEO_ASPECT_RATIO}"
-    conf_variable_write MM_VIDEO_DEINTERLACE_ENABLED "${MM_VIDEO_DEINTERLACE_ENABLED}"
+    conf_variable_write "${conf_file}" MM_VIDEO_ASPECT_RATIO        "${MM_VIDEO_ASPECT_RATIO}"
+    conf_variable_write "${conf_file}" MM_VIDEO_DEINTERLACE_ENABLED "${MM_VIDEO_DEINTERLACE_ENABLED}"
 
     # X.
     case "${MM_HARDWARE_NORTHBRIDGE}" in
@@ -265,22 +294,22 @@ conf_write() {
             esac
         fi
     fi
-    conf_variable_write MM_X_DRIVER        "${MM_X_DRIVER}"
-    conf_variable_write MM_X_ENABLED       "${MM_X_ENABLED}"
-    conf_variable_write MM_X_WM_ENABLED    "${MM_X_WM_ENABLED}"
-    conf_variable_write MM_X_VNC_ENABLED   "${MM_X_VNC_ENABLED}"
-    conf_variable_write MM_X_DVI_ENABLED   "${MM_X_DVI_ENABLED}"
-    conf_variable_write MM_X_VGA_ENABLED   "${MM_X_VGA_ENABLED}"
-    conf_variable_write MM_X_TV_ENABLED    "${MM_X_TV_ENABLED}"
-    conf_variable_write MM_X_TV_TYPE       "${MM_X_TV_TYPE}"
-    conf_variable_write MM_X_TV_OUTPUT     "${MM_X_TV_OUTPUT}"
-    conf_variable_write MM_X_REFRESH       "${MM_X_REFRESH}"
-    conf_variable_write MM_X_MODE          "${MM_X_MODE}"
-    conf_variable_write MM_X_MODELINE      "${MM_X_MODELINE}"
-    conf_variable_write MM_X_RESOLUTION_X  "${MM_X_RESOLUTION_X}"
-    conf_variable_write MM_X_RESOLUTION_Y  "${MM_X_RESOLUTION_Y}"
-    conf_variable_write MM_X_DISPLAYSIZE_X "${MM_X_DISPLAYSIZE_X}"
-    conf_variable_write MM_X_DISPLAYSIZE_Y "${MM_X_DISPLAYSIZE_Y}"
+    conf_variable_write "${conf_file}" MM_X_DRIVER        "${MM_X_DRIVER}"
+    conf_variable_write "${conf_file}" MM_X_ENABLED       "${MM_X_ENABLED}"
+    conf_variable_write "${conf_file}" MM_X_WM_ENABLED    "${MM_X_WM_ENABLED}"
+    conf_variable_write "${conf_file}" MM_X_VNC_ENABLED   "${MM_X_VNC_ENABLED}"
+    conf_variable_write "${conf_file}" MM_X_DVI_ENABLED   "${MM_X_DVI_ENABLED}"
+    conf_variable_write "${conf_file}" MM_X_VGA_ENABLED   "${MM_X_VGA_ENABLED}"
+    conf_variable_write "${conf_file}" MM_X_TV_ENABLED    "${MM_X_TV_ENABLED}"
+    conf_variable_write "${conf_file}" MM_X_TV_TYPE       "${MM_X_TV_TYPE}"
+    conf_variable_write "${conf_file}" MM_X_TV_OUTPUT     "${MM_X_TV_OUTPUT}"
+    conf_variable_write "${conf_file}" MM_X_REFRESH       "${MM_X_REFRESH}"
+    conf_variable_write "${conf_file}" MM_X_MODE          "${MM_X_MODE}"
+    conf_variable_write "${conf_file}" MM_X_MODELINE      "${MM_X_MODELINE}"
+    conf_variable_write "${conf_file}" MM_X_RESOLUTION_X  "${MM_X_RESOLUTION_X}"
+    conf_variable_write "${conf_file}" MM_X_RESOLUTION_Y  "${MM_X_RESOLUTION_Y}"
+    conf_variable_write "${conf_file}" MM_X_DISPLAYSIZE_X "${MM_X_DISPLAYSIZE_X}"
+    conf_variable_write "${conf_file}" MM_X_DISPLAYSIZE_Y "${MM_X_DISPLAYSIZE_Y}"
 
     # Myth master backend.
     [ -z "${MM_MYTH_SERVER}"                  ] && MM_MYTH_SERVER="${MM_TFTP_SERVER}"
@@ -292,15 +321,15 @@ conf_write() {
     [ -z "${MM_MYTH_WOLSQLRECONNECTWAITTIME}" ] && MM_MYTH_WOLSQLRECONNECTWAITTIME="15"
     [ -z "${MM_MYTH_WOLSQLCONNECTRETRY}"      ] && MM_MYTH_WOLSQLCONNECTRETRY="20"
     [ -z "${MM_MYTH_WOLSQLCOMMAND}"           ] && MM_MYTH_WOLSQLCOMMAND="wakelan -b @MM_MYTH_WOL_BROADCAST@ -m @MM_MYTH_WOL_MAC@"
-    conf_variable_write MM_MYTH_SERVER                  "${MM_MYTH_SERVER}"
-    conf_variable_write MM_MYTH_DBUSERNAME              "${MM_MYTH_DBUSERNAME}"
-    conf_variable_write MM_MYTH_DBPASSWORD              "${MM_MYTH_DBPASSWORD}"
-    conf_variable_write MM_MYTH_DBNAME                  "${MM_MYTH_DBNAME}"
-    conf_variable_write MM_MYTH_WOL_ENABLED             "${MM_MYTH_WOL_ENABLED}"
-    conf_variable_write MM_MYTH_WOL_MAC                 "${MM_MYTH_WOL_MAC}"
-    conf_variable_write MM_MYTH_WOLSQLRECONNECTWAITTIME "${MM_MYTH_WOLSQLRECONNECTWAITTIME}"
-    conf_variable_write MM_MYTH_WOLSQLCONNECTRETRY      "${MM_MYTH_WOLSQLCONNECTRETRY}"
-    conf_variable_write MM_MYTH_WOLSQLCOMMAND           "${MM_MYTH_WOLSQLCOMMAND}"
+    conf_variable_write "${conf_file}" MM_MYTH_SERVER                  "${MM_MYTH_SERVER}"
+    conf_variable_write "${conf_file}" MM_MYTH_DBUSERNAME              "${MM_MYTH_DBUSERNAME}"
+    conf_variable_write "${conf_file}" MM_MYTH_DBPASSWORD              "${MM_MYTH_DBPASSWORD}"
+    conf_variable_write "${conf_file}" MM_MYTH_DBNAME                  "${MM_MYTH_DBNAME}"
+    conf_variable_write "${conf_file}" MM_MYTH_WOL_ENABLED             "${MM_MYTH_WOL_ENABLED}"
+    conf_variable_write "${conf_file}" MM_MYTH_WOL_MAC                 "${MM_MYTH_WOL_MAC}"
+    conf_variable_write "${conf_file}" MM_MYTH_WOLSQLRECONNECTWAITTIME "${MM_MYTH_WOLSQLRECONNECTWAITTIME}"
+    conf_variable_write "${conf_file}" MM_MYTH_WOLSQLCONNECTRETRY      "${MM_MYTH_WOLSQLCONNECTRETRY}"
+    conf_variable_write "${conf_file}" MM_MYTH_WOLSQLCOMMAND           "${MM_MYTH_WOLSQLCOMMAND}"
 
     # Myth plugins.
     [ -z "${MM_MYTHTV_OPTICAL_DISK_ENABLED}" ] && MM_MYTHTV_OPTICAL_DISK_ENABLED="yes"
@@ -309,31 +338,31 @@ conf_write() {
     [ -z "${MM_MYTHMUSIC_ENABLED}"           ] && MM_MYTHMUSIC_ENABLED="yes"
     [ -z "${MM_MYTHVIDEO_ENABLED}"           ] && MM_MYTHVIDEO_ENABLED="yes"
     [ -z "${MM_MYTHWEATHER_ENABLED}"         ] && MM_MYTHWEATHER_ENABLED="yes"
-    conf_variable_write MM_MYTHTV_OPTICAL_DISK_ENABLED "${MM_MYTHTV_OPTICAL_DISK_ENABLED}"
-    conf_variable_write MM_MYTHDVD_ENABLED             "${MM_MYTHDVD_ENABLED}"
-    conf_variable_write MM_MYTHGALLERY_ENABLED         "${MM_MYTHGALLERY_ENABLED}"
-    conf_variable_write MM_MYTHMUSIC_ENABLED           "${MM_MYTHMUSIC_ENABLED}"
-    conf_variable_write MM_MYTHVIDEO_ENABLED           "${MM_MYTHVIDEO_ENABLED}"
-    conf_variable_write MM_MYTHWEATHER_ENABLED         "${MM_MYTHWEATHER_ENABLED}"
+    conf_variable_write "${conf_file}" MM_MYTHTV_OPTICAL_DISK_ENABLED "${MM_MYTHTV_OPTICAL_DISK_ENABLED}"
+    conf_variable_write "${conf_file}" MM_MYTHDVD_ENABLED             "${MM_MYTHDVD_ENABLED}"
+    conf_variable_write "${conf_file}" MM_MYTHGALLERY_ENABLED         "${MM_MYTHGALLERY_ENABLED}"
+    conf_variable_write "${conf_file}" MM_MYTHMUSIC_ENABLED           "${MM_MYTHMUSIC_ENABLED}"
+    conf_variable_write "${conf_file}" MM_MYTHVIDEO_ENABLED           "${MM_MYTHVIDEO_ENABLED}"
+    conf_variable_write "${conf_file}" MM_MYTHWEATHER_ENABLED         "${MM_MYTHWEATHER_ENABLED}"
 
     # Extras.
-    conf_variable_write MM_EXTRAS_URL "${MM_EXTRAS_URL}"
+    conf_variable_write "${conf_file}" MM_EXTRAS_URL "${MM_EXTRAS_URL}"
 
     # Codecs.
-    conf_variable_write MM_CODECS_URL "${MM_CODECS_URL}"
+    conf_variable_write "${conf_file}" MM_CODECS_URL "${MM_CODECS_URL}"
 
     # Themes.
-    conf_variable_write MM_THEME_NAME     "${MM_THEME_NAME}"
-    conf_variable_write MM_THEMEOSD_NAME  "${MM_THEMEOSD_NAME}"
-    conf_variable_write MM_THEME_URL      "${MM_THEME_URL}"
-    conf_variable_write MM_THEMEOSD_URL   "${MM_THEMEOSD_URL}"
-    conf_variable_write MM_THEMECACHE_URL "${MM_THEMECACHE_URL}"
+    conf_variable_write "${conf_file}" MM_THEME_NAME     "${MM_THEME_NAME}"
+    conf_variable_write "${conf_file}" MM_THEMEOSD_NAME  "${MM_THEMEOSD_NAME}"
+    conf_variable_write "${conf_file}" MM_THEME_URL      "${MM_THEME_URL}"
+    conf_variable_write "${conf_file}" MM_THEMEOSD_URL   "${MM_THEMEOSD_URL}"
+    conf_variable_write "${conf_file}" MM_THEMECACHE_URL "${MM_THEMECACHE_URL}"
 
     # Media shares.
-    conf_variable_write MM_MYTHDVD_URL     "${MM_MYTHDVD_URL}"
-    conf_variable_write MM_MYTHGALLERY_URL "${MM_MYTHGALLERY_URL}"
-    conf_variable_write MM_MYTHMUSIC_URL   "${MM_MYTHMUSIC_URL}"
-    conf_variable_write MM_MYTHVIDEO_URL   "${MM_MYTHVIDEO_URL}"
+    conf_variable_write "${conf_file}" MM_MYTHDVD_URL     "${MM_MYTHDVD_URL}"
+    conf_variable_write "${conf_file}" MM_MYTHGALLERY_URL "${MM_MYTHGALLERY_URL}"
+    conf_variable_write "${conf_file}" MM_MYTHMUSIC_URL   "${MM_MYTHMUSIC_URL}"
+    conf_variable_write "${conf_file}" MM_MYTHVIDEO_URL   "${MM_MYTHVIDEO_URL}"
 
     # LIRC.
     case "${MM_LIRC_DRIVER}" in
@@ -374,12 +403,12 @@ conf_write() {
             ;;
     esac
     [ -z "${MM_LIRC_IREXEC_ENABLED}" ] && MM_LIRC_IREXEC_ENABLED="no"
-    conf_variable_write MM_LIRC_REMOTE                "${MM_LIRC_REMOTE}"
-    conf_variable_write MM_LIRC_DRIVER                "${MM_LIRC_DRIVER}"
-    conf_variable_write MM_LIRC_DEVICE                "${MM_LIRC_DEVICE}"
-    conf_variable_write MM_LIRC_KERNEL_MODULE         "${MM_LIRC_KERNEL_MODULE}"
-    conf_variable_write MM_LIRC_KERNEL_MODULE_OPTIONS "${MM_LIRC_KERNEL_MODULE_OPTIONS}"
-    conf_variable_write MM_LIRC_IREXEC_ENABLED        "${MM_LIRC_IREXEC_ENABLED}"
+    conf_variable_write "${conf_file}" MM_LIRC_REMOTE                "${MM_LIRC_REMOTE}"
+    conf_variable_write "${conf_file}" MM_LIRC_DRIVER                "${MM_LIRC_DRIVER}"
+    conf_variable_write "${conf_file}" MM_LIRC_DEVICE                "${MM_LIRC_DEVICE}"
+    conf_variable_write "${conf_file}" MM_LIRC_KERNEL_MODULE         "${MM_LIRC_KERNEL_MODULE}"
+    conf_variable_write "${conf_file}" MM_LIRC_KERNEL_MODULE_OPTIONS "${MM_LIRC_KERNEL_MODULE_OPTIONS}"
+    conf_variable_write "${conf_file}" MM_LIRC_IREXEC_ENABLED        "${MM_LIRC_IREXEC_ENABLED}"
 
     return 0
 }
@@ -396,8 +425,11 @@ start() {
         exit 1
     fi
 
-    conf_init
+    core_check
+    dhcp_check
     conf_check
+
+    conf_init
     conf_write
 
     return 0
