perforce changeset 627

diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/lirc b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/lirc
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/lirc
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/lirc
@@ -33,12 +33,17 @@ start() {
         mkdir -p /var/lock
         mkdir -p /var/run
 
-        # Wait up to 10 seconds for the device to appear in the device file system.
+        # Wait up to 60 seconds for the device to appear in the device file system.
         DELAY=0
-        while [ ! -e ${MM_LIRC_DEVICE} ] && [ ${DELAY} -lt 10 ] ; do
+        while [ ! -e ${MM_LIRC_DEVICE} ] && [ ${DELAY} -lt 60 ] ; do
             sleep 1
             DELAY=$((DELAY + 1))
+            mm_message_output info "waiting for remote control device (${DELAY} seconds) ..."
         done
+        if [ ! -e ${MM_LIRC_DEVICE} ] ; then
+            mm_message_output err 'error: timed out waiting for remote control device.'
+            exit 1
+        fi
 
         LIRC_DRIVER=`lircd --driver=help 2>&1 | grep "${MM_LIRC_DRIVER}"`
         [ -z ${LIRC_DRIVER} ] && LIRC_DRIVER="default"
