perforce changeset 807

diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/modules b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/modules
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/modules
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/modules
@@ -13,6 +13,13 @@ start() {
     # IO scheduler.
     modprobe as-iosched
 
+    # Load ACPI kernel modules.
+    modprobe button
+    modprobe fan
+    modprobe processor
+    modprobe thermal
+    modprobe video
+
     # Input.
     modprobe evdev
     modprobe psmouse
@@ -28,65 +35,13 @@ start() {
     modprobe parport_pc
     modprobe ppdev
 
-    # Look for PCI devices and load associated drivers.
-    lspci -mn | sed -e 's%"%%g' | while read pci ; do
-        index=1            ; bus=`       echo "${pci}" | cut -d' ' -f${index}`
-        index=$((index+1)) ; class=`     echo "${pci}" | cut -d' ' -f${index}`
-        index=$((index+1)) ; vendor=`    echo "${pci}" | cut -d' ' -f${index}`
-        index=$((index+1)) ; device=`    echo "${pci}" | cut -d' ' -f${index}`
-        index=$((index+1)) ; revision=`  echo "${pci}" | cut -d' ' -f${index}`
-        if [ `echo "${revision}"   | grep -c -e '^-r'` = "1" ] ; then
-            revision=`  echo "${revision}"   | sed -e 's%^-r%%'`
-        else
-            index=$((index-1)) ; revision=
+    # Detected and user specified kernel modules.
+    for kernel_module in ${MM_KERNEL_MODULES} ; do
+        modprobe ${kernel_module}
+        if [ ! "$?" = "0" ] ; then
+            mm_message_output err "error: failed to load kernel module: ${kernel_module}"
+            exit 1
         fi
-        index=$((index+1)) ; class_prog=`echo "${pci}" | cut -d' ' -f${index}`
-        if [ `echo "${class_prog}" | grep -c -e '^-p'` = "1" ] ; then
-            class_prog=`echo "${class_prog}" | sed -e 's%^-p%%'`
-        else
-            index=$((index-1)) ; class_prog=
-        fi
-        index=$((index+1)) ; sub_vendor=`echo "${pci}" | cut -d' ' -f${index}`
-        index=$((index+1)) ; sub_device=`echo "${pci}" | cut -d' ' -f${index}`
-
-        case "${class}" in
-            # PCI bridge (assumed to imply AGP).
-            0604)
-                case "${vendor}" in
-                    8086) modprobe intel-agp  ;; # Intel
-                    10de) modprobe nvidia-agp ;; # NVIDIA
-                    1106) modprobe via-agp    ;; # VIA
-                esac
-                ;;
-            # IDE.
-            0101)
-                case "${vendor}" in
-                    8086) modprobe piix      ;; # Intel
-                    10de) modprobe amd74xx   ;; # NVIDIA
-                    1106) modprobe via82cxxx ;; # VIA
-                esac
-                ;;
-            # FireWire (IEEE1394).
-            0c00)
-                [ -z "${class_prog}" ] && class_prog="00"
-                case "${class_prog}" in
-                    00) modprobe ieee1394 ;;
-                    10) modprobe ohci1394 ;;
-                esac
-                ;;
-            # USB.
-            0c03)
-                [ -z "${class_prog}" ] && class_prog="00"
-                case "${class_prog}" in
-                    00) modprobe uhci-hcd ;;
-                    10) modprobe ohci-hcd ;;
-                    20) modprobe ehci-hcd ;;
-                esac
-                ;;
-            # SMBus.
-            0c05)
-                ;;
-        esac
     done
 
     # IDE.
diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/video b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/video
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/video
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/video
@@ -9,6 +9,11 @@
 start() {
     mm_message_output info 'configuring video ...'
 
+    if [ -z "${MM_X_DRIVER}" ] ; then
+        mm_message_output err "error: no supported video hardware found."
+        exit 1
+    fi
+
     if   [ "${MM_VIDEO_ASPECT_RATIO}" = "4:3"  ] ; then
         sed -i "s%@MONITORASPECT@%4:3%"  /root/.mplayer/config
     elif [ "${MM_VIDEO_ASPECT_RATIO}" = "16:9" ] ; then
@@ -44,7 +49,6 @@ start() {
             sed -i "s%@XVMC_FALSE@%%"                    /root/.mplayer/config
             ;;
         intel_i810)
-            modprobe i810
             sed -i "s%@MM_XVMC_LIB@%I810XvMC%"           /etc/X11/XvMCConfig
             PREFERRED_MPEG2_DECODER=xvmc
             sed -i "s%@VIDEO_DRIVER@%xvmc%"              /root/.xine/config
@@ -54,7 +58,6 @@ start() {
             sed -i "s%@XVMC_FALSE@%\#%"                  /root/.mplayer/config
             ;;
         intel_i830)
-            modprobe i830
             PREFERRED_MPEG2_DECODER=ffmpeg
             sed -i "s%@VIDEO_DRIVER@%xv%"                /root/.xine/config
             sed -i "s%@XVMC_TRUE@%\#%"                   /root/.xine/config
@@ -63,7 +66,6 @@ start() {
             sed -i "s%@XVMC_FALSE@%%"                    /root/.mplayer/config
             ;;
         intel_i915)
-            modprobe i915
             PREFERRED_MPEG2_DECODER=ffmpeg
             sed -i "s%@VIDEO_DRIVER@%xv%"                /root/.xine/config
             sed -i "s%@XVMC_TRUE@%\#%"                   /root/.xine/config
@@ -72,7 +74,6 @@ start() {
             sed -i "s%@XVMC_FALSE@%%"                    /root/.mplayer/config
             ;;
         nvidia)
-            modprobe nvidia
             sed -i "s%@MM_XVMC_LIB@%XvMCNVIDIA_dynamic%" /etc/X11/XvMCConfig
             # this should really be the more efficient 'libmpeg2',
             # but it causes stalls during when fast forwarding and rewinding.
@@ -84,7 +85,6 @@ start() {
             sed -i "s%@XVMC_FALSE@%%"                    /root/.mplayer/config
             ;;
         via)
-            modprobe via
             sed -i "s%@MM_XVMC_LIB@%viaXvMC%"            /etc/X11/XvMCConfig
             PREFERRED_MPEG2_DECODER=xvmc-vld
             sed -i "s%@VIDEO_DRIVER@%xxmc%"              /root/.xine/config
@@ -94,7 +94,6 @@ start() {
             sed -i "s%@XVMC_FALSE@%\#%"                  /root/.mplayer/config
             ;;
         via_pro)
-            modprobe via
             sed -i "s%@MM_XVMC_LIB@%viaXvMCPro%"         /etc/X11/XvMCConfig
             PREFERRED_MPEG2_DECODER=xvmc-vld
             sed -i "s%@VIDEO_DRIVER@%xxmc%"              /root/.xine/config
