Changed time init script to fail when ntpdate fails.

diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/time b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/time
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/time
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/time
@@ -40,6 +40,10 @@ start() {
 
     # Set time.
     /usr/bin/ntpdate ${NTP_SERVER}
+    if /usr/bin/test $? -ne 0 ; then
+        mm_message_output err "error: 'ntpdate' failed to synchronize with '${NTP_SERVER}'."
+        exit 1
+    fi
 
     # Start NTP daemon.
     /usr/bin/ntpd
