perforce changeset 590

diff --git a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/x b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/x
--- a/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/x
+++ b/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/x
@@ -10,31 +10,6 @@ start() {
     mm_conf_get /xinitrc /root/.xinitrc
     mm_conf_get /xorg.conf /etc/X11/xorg.conf
 
-    if   [ "${MM_X_VGA_ENABLED}" = "no"  ] && [ "${MM_X_TV_ENABLED}" = "no"  ] ; then
-        mm_message_output err 'error: no X video output enabled'
-        exit 1
-    elif [ "${MM_X_VGA_ENABLED}" = "yes" ] && [ "${MM_X_TV_ENABLED}" = "no"  ] ; then
-        MM_X_DEVICE="CRT"
-    elif [ "${MM_X_VGA_ENABLED}" = "no"  ] && [ "${MM_X_TV_ENABLED}" = "yes" ] ; then
-        MM_X_DEVICE="TV"
-    elif [ "${MM_X_VGA_ENABLED}" = "yes" ] && [ "${MM_X_TV_ENABLED}" = "yes" ] ; then
-        MM_X_DEVICE="CRT,TV"
-    fi
-
-    # Override MM_X_MODE and MM_X_MODELINE if MM_X_RESOLUTION_X and MM_X_RESOLUTION_Y are set.
-    if   [ ! -z "${MM_X_RESOLUTION_X}" ] && [ ! -z "${MM_X_RESOLUTION_Y}" ] ; then
-        MM_X_MODELINE=`gtf ${MM_X_RESOLUTION_X} ${MM_X_RESOLUTION_Y} ${MM_X_REFRESH} | sed 's% *#.*%%'`
-        MM_X_MODELINE=`echo ${MM_X_MODELINE}`
-        MM_X_MODE=`echo ${MM_X_MODELINE} | sed 's%^Modeline "\([^"]*\)".*%\1%'`
-    fi
-
-    # Set MM_X_DISPLAYSIZE
-    if   [ ! -z "${MM_X_DISPLAYSIZE_X}" ] && [ ! -z "${MM_X_DISPLAYSIZE_Y}" ] ; then
-        MM_X_DISPLAYSIZE="DisplaySize ${MM_X_DISPLAYSIZE_X} ${MM_X_DISPLAYSIZE_Y}"
-    else
-        MM_X_DISPLAYSIZE=
-    fi
-
     case "${MM_HARDWARE_NORTHBRIDGE}" in
         CLE266)
             MM_X_DRIVER=via
@@ -49,6 +24,52 @@ start() {
             MM_X_DRIVER=nvidia
             ;;
     esac
+
+    MM_X_DEVICE_NVIDIA=""
+    MM_X_DEVICE_VIA=""
+    if [ "${MM_X_TV_ENABLED}"  = yes ] ; then
+        MM_X_DEVICE_NVIDIA="TV"
+        [ -n "${MM_X_DEVICE_VIA}" ] && MM_X_DEVICE_VIA=",${MM_X_DEVICE_VIA}"
+        MM_X_DEVICE_VIA="TV${MM_X_DEVICE_VIA}"
+    fi
+    if [ "${MM_X_VGA_ENABLED}" = yes ] ; then
+        MM_X_DEVICE_NVIDIA="CRT"
+        [ -n "${MM_X_DEVICE_VIA}" ] && MM_X_DEVICE_VIA=",${MM_X_DEVICE_VIA}"
+        MM_X_DEVICE_VIA="CRT${MM_X_DEVICE_VIA}"
+    fi
+    if [ "${MM_X_DVI_ENABLED}" = yes ] ; then
+        MM_X_DEVICE_NVIDIA="DFP"
+        [ -n "${MM_X_DEVICE_VIA}" ] && MM_X_DEVICE_VIA=",${MM_X_DEVICE_VIA}"
+        MM_X_DEVICE_VIA="LCD${MM_X_DEVICE_VIA}"
+    fi
+    case "${MM_X_DRIVER}" in
+        nvidia)
+            if [ ! -n "${MM_X_DEVICE_NVIDIA}" ] ; then
+                mm_message_output err 'error: no X video output enabled'
+                exit 1
+            fi
+            ;;
+        via)
+            if [ ! -n "${MM_X_DEVICE_VIA}"    ] ; then
+                mm_message_output err 'error: no X video output enabled'
+                exit 1
+            fi
+            ;;
+    esac
+
+    # Override MM_X_MODE and MM_X_MODELINE if MM_X_RESOLUTION_X and MM_X_RESOLUTION_Y are set.
+    if   [ ! -z "${MM_X_RESOLUTION_X}" ] && [ ! -z "${MM_X_RESOLUTION_Y}" ] ; then
+        MM_X_MODELINE=`gtf ${MM_X_RESOLUTION_X} ${MM_X_RESOLUTION_Y} ${MM_X_REFRESH} | sed 's% *#.*%%'`
+        MM_X_MODELINE=`echo ${MM_X_MODELINE}`
+        MM_X_MODE=`echo ${MM_X_MODELINE} | sed 's%^Modeline "\([^"]*\)".*%\1%'`
+    fi
+
+    # Set MM_X_DISPLAYSIZE
+    if   [ ! -z "${MM_X_DISPLAYSIZE_X}" ] && [ ! -z "${MM_X_DISPLAYSIZE_Y}" ] ; then
+        MM_X_DISPLAYSIZE="DisplaySize ${MM_X_DISPLAYSIZE_X} ${MM_X_DISPLAYSIZE_Y}"
+    else
+        MM_X_DISPLAYSIZE=
+    fi
 
     # Hacks to deal with the fact that the proprietary NVIDIA GL libraries
     # conflict with the Open Source Mesa GL libraries.
@@ -78,16 +99,17 @@ start() {
             ;;
     esac
 
-    sed -i "s%@MM_X_DRIVER@%${MM_X_DRIVER}%"           /etc/X11/xorg.conf
-    sed -i "s%@MM_X_DEVICE@%${MM_X_DEVICE}%"           /etc/X11/xorg.conf
-    sed -i "s%@MM_X_TV_TYPE@%${MM_X_TV_TYPE}%"         /etc/X11/xorg.conf
-    sed -i "s%@MM_X_TV_OUTPUT@%${MM_X_TV_OUTPUT}%"     /etc/X11/xorg.conf
-    sed -i "s%@MM_X_REFRESH@%${MM_X_REFRESH}%"         /etc/X11/xorg.conf
-    sed -i "s%@MM_X_MODELINE@%${MM_X_MODELINE}%"       /etc/X11/xorg.conf
-    sed -i "s%@MM_X_MODE@%${MM_X_MODE}%"               /etc/X11/xorg.conf
-    sed -i "s%@MM_X_DISPLAYSIZE@%${MM_X_DISPLAYSIZE}%" /etc/X11/xorg.conf
-    sed -i "s%@MM_X_MODULE_DRI@%${MM_X_MODULE_DRI}%"   /etc/X11/xorg.conf
-    sed -i "s%@MM_X_MODULEPATH@%${MM_X_MODULEPATH}%"   /etc/X11/xorg.conf
+    sed -i "s%@MM_X_DRIVER@%${MM_X_DRIVER}%"               /etc/X11/xorg.conf
+    sed -i "s%@MM_X_DEVICE_NVIDIA@%${MM_X_DEVICE_NVIDIA}%" /etc/X11/xorg.conf
+    sed -i "s%@MM_X_DEVICE_VIA@%${MM_X_DEVICE_VIA}%"       /etc/X11/xorg.conf
+    sed -i "s%@MM_X_TV_TYPE@%${MM_X_TV_TYPE}%"             /etc/X11/xorg.conf
+    sed -i "s%@MM_X_TV_OUTPUT@%${MM_X_TV_OUTPUT}%"         /etc/X11/xorg.conf
+    sed -i "s%@MM_X_REFRESH@%${MM_X_REFRESH}%"             /etc/X11/xorg.conf
+    sed -i "s%@MM_X_MODELINE@%${MM_X_MODELINE}%"           /etc/X11/xorg.conf
+    sed -i "s%@MM_X_MODE@%${MM_X_MODE}%"                   /etc/X11/xorg.conf
+    sed -i "s%@MM_X_DISPLAYSIZE@%${MM_X_DISPLAYSIZE}%"     /etc/X11/xorg.conf
+    sed -i "s%@MM_X_MODULE_DRI@%${MM_X_MODULE_DRI}%"       /etc/X11/xorg.conf
+    sed -i "s%@MM_X_MODULEPATH@%${MM_X_MODULEPATH}%"       /etc/X11/xorg.conf
 
     # Turn off splash screen.
     mm_splash_halt
