Added security     - Added PAM support.         - Added PAM.         - Enabled PAM support in busybox telnet.         - Enabled PAM support in dropbear.     - Added LDAP authentication.         - Added nss_ldap.             - Patched to override non-existent home directories and shells.         - Added pam_ldap.         - Added MM_AUTH_LDAP_* to configure LDAP authentication.     - Added SSH server (dropbear).     - Made some of the file system permissions more strict.     - Added MM_SECURITY_* to configure security.         - Disabled telnet and web access to the file system when security           is enabled.     - Added MM_AUTH_* to configure authentication. Added packages     - 'lib/openldap'     - 'system/nss_ldap'     - 'system/pam'     - 'system/pam_ldap' Patched problems in packages     - 'devel/flex'     - 'lib/openssl'

diff --git a/gar-minimyth/script/meta/minimyth/dirs/usr/bin/mm_ssh b/gar-minimyth/script/meta/minimyth/dirs/usr/bin/mm_ssh
--- a/gar-minimyth/script/meta/minimyth/dirs/usr/bin/mm_ssh
+++ b/gar-minimyth/script/meta/minimyth/dirs/usr/bin/mm_ssh
@@ -1,3 +1,17 @@
 #!/bin/sh
 
+. /etc/rc.d/functions
+
+if /usr/bin/test ! "${MM_SSH_REMOTE_ENABLED}" = "yes" ; then
+    /usr/bin/logger -t minimyth -p "local0.error" \
+         "mm_ssh: ssh client has not been enabled."
+    exit 1
+fi
+
+if /usr/bin/test -r /etc/dropbear/id_rsa ; then
+    /usr/bin/logger -t minimyth -p "local0.error" \
+         "mm_ssh: ssh user does not have access to the ssh identity."
+    exit 1
+fi
+
 /usr/bin/dbclient -y -i /etc/dropbear/id_rsa "$@"
