- Improved DHCP support.   - Use first connected network interface rather than eth0. - Added packages 'lib/libdaemon' and 'net/ifplugd'.

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/dhcp b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/dhcp
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/dhcp
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/dhcp
@@ -7,6 +7,9 @@
 start() {
 
     local DHCLIENT_CONF
+    local INTERFACE
+    local INTERFACE_ITEM
+    local INTERFACE_LIST
     local IP_ADDRESS
 
     DHCLIENT_CONF='/etc/dhclient.conf'
@@ -85,19 +88,42 @@ start() {
 
     # Start 'dhclient'.
     if /usr/bin/test -z "`/bin/pidof dhclient`" ; then
-        /bin/mkdir -p /var/db
-        /usr/sbin/dhclient eth0
-        if /usr/bin/test $? -ne 0 ; then
-            mm_message_output err "error: DHCP failed."
+        INTERFACE=${MM_NETWORK_INTERFACE}
+        if /usr/bin/test -z "${INTERFACE}" ; then
+            # Locate a connected network interface.
+            # We use the first connected network interface found.
+            INTERFACE_LIST=
+            if /usr/bin/test -e /sys/class/net ; then
+                INTERFACE_LIST=`/bin/ls -1 /sys/class/net | /bin/grep -v '^lo$'`
+            fi
+            INTERFACE=
+            for INTERFACE_ITEM in ${INTERFACE_LIST} ; do
+                /usr/sbin/ifplugstatus -q ${INTERFACE_ITEM}
+                if /usr/bin/test $? -eq 2 ; then
+                    INTERFACE=${INTERFACE_ITEM}
+                    break
+                fi
+            done
+        fi
+        if /usr/bin/test -z "${INTERFACE}" ; then
+            mm_message_output err "error: no valid network interface found."
             exit 1
         fi
-    fi
 
-    # Make sure we got an IP address.
-    IP_ADDRESS=`/sbin/ifconfig eth0 | /bin/grep '^ *inet addr:' | /bin/sed 's%^ *inet addr:\([^ ]*\) .*%\1%'`
-    if /usr/bin/test -z "${IP_ADDRESS}" ; then
-        mm_message_output err "error: DHCP failed."
-        exit 1
+        # Start DHCP on the interface.
+        /bin/mkdir -p /var/db
+        /usr/sbin/dhclient ${INTERFACE}
+        if /usr/bin/test $? -ne 0 ; then
+            mm_message_output err "error: DHCP on interface '${INTERFACE}' failed."
+            exit 1
+        fi
+
+        # Make sure we got an IP address.
+        IP_ADDRESS=`/sbin/ifconfig ${INTERFACE} | /bin/grep '^ *inet addr:' | /bin/sed 's%^ *inet addr:\([^ ]*\) .*%\1%'`
+        if /usr/bin/test -z "${IP_ADDRESS}" ; then
+            mm_message_output err "error: DHCP on interface '${INTERFACE}' failed."
+            exit 1
+        fi
     fi
 
     return 0
