- Added variables MM_LCDPROC_DEVICE, MM_LCDPROC_KERNEL_MODULE and   MM_LCDPROC_KERNEL_MODULE_OPTIONS for providing better configuration of   LCDproc devices.

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/lcdproc b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/lcdproc
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/lcdproc
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/lcdproc
@@ -9,6 +9,22 @@ start() {
 
     # Only start the LCDd daemon when one is not running already.
     if /usr/bin/test -z "`/bin/pidof LCDd`" ; then
+        # Load user configured kernel module.
+        if /usr/bin/test -n "${MM_LCDPROC_KERNEL_MODULE}" ; then
+            /sbin/modprobe ${MM_LCDPROC_KERNEL_MODULE} ${MM_LCDPROC_KERNEL_MODULE_OPTIONS}
+            # Wait up to 60 seconds for the device to appear in the device file system.
+            delay=0
+            while /usr/bin/test ! -e ${MM_LCDPROC_DEVICE} && /usr/bin/test ${delay} -lt 60 ; do
+                /bin/sleep 1
+                delay=$((delay + 1))
+                mm_message_output info "waiting for LCD/VFD device (${delay} seconds) ..."
+            done
+            if /usr/bin/test ! -e ${MM_LCDPROC_DEVICE} ; then
+                mm_message_output err "error: timed out waiting for LCD/VFD device."
+                exit 1
+            fi
+        fi
+
         # Load the LCDproc configuration file.
         if /usr/bin/test ! -e /etc/LCDd.conf ; then
             if /usr/bin/test -n "${MM_LCDPROC_DRIVER}" ; then
@@ -22,7 +38,13 @@ start() {
 
         if /usr/bin/test -e /etc/LCDd.conf ; then
             # Set the driver.
-            /bin/sed -i "s%@MM_LCDPROC_DRIVER@%${MM_LCDPROC_DRIVER}%" /etc/LCDd.conf
+            if /usr/bin/test -n "${MM_LCDPROC_Driver}" ; then
+                /bin/sed -i "s%^Driver=.*$%Driver=${MM_LCDPROC_DRIVER}%" /etc/LCDd.conf
+            fi
+            # Set the device.
+            if /usr/bin/test -n "${MM_LCDPROC_DEVICE}" ; then
+                /bin/sed -i s%^Device=.*$%Device=${MM_LCDPROC_DEVICE} /etc/LCDd.conf
+            fi
             # Start LCDproc LCDd daemon and Myth LCD server.
             /usr/sbin/LCDd -c /etc/LCDd.conf
         fi
