- Fixed bug in DVD rip init error handling.

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/mythtv b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/mythtv
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/mythtv
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/mythtv
@@ -61,37 +61,48 @@ start() {
     # Configure MythDVD ripping.
     # Since mythfrontend is run as user 'minimyth', mtd is run as user 'minimyth'.
     # As a result, it is user 'minimyth' that must have the required read-write access.
-    if ( /usr/bin/test ${MM_VERSION_MYTH_BINARY_MAJOR} -eq 0  && \
-         /usr/bin/test ${MM_VERSION_MYTH_BINARY_MINOR} -eq 20 && \
-         /usr/bin/test "${MM_MYTHDVD_ENABLED}" = "yes"           ) ||
-       ( /usr/bin/test ${MM_VERSION_MYTH_BINARY_MAJOR} -eq 0  && \
-         /usr/bin/test ${MM_VERSION_MYTH_BINARY_MINOR} -eq 21 && \
-         /usr/bin/test "${MM_MYTHVIDEO_ENABLED}" = "yes"         ) ; then
-        if /bin/su -c "/usr/bin/test -d ${MM_MYTHDVD_MOUNTPOINT}" - minimyth ; then
-            if /bin/su -c "/usr/bin/test -w ${MM_MYTHDVD_MOUNTPOINT}" - minimyth ; then
-                /bin/su -c "/bin/mkdir -p ${MM_MYTHDVD_MOUNTPOINT}/.mtd" - minimyth
-            else
-                /usr/bin/logger -t minimyth -p "local0.err" \
-                    "error: '${MM_MYTHDVD_MOUNTPOINT}' exists but is not writable by user 'minimyth'."
-                exit 1
-            fi
-        fi
-        if /bin/su -c "/usr/bin/test -d ${MM_MYTHDVD_MOUNTPOINT}/.mtd" - minimyth ; then
-            if /bin/su -c "/usr/bin/test -w ${MM_MYTHDVD_MOUNTPOINT}/.mtd" - minimyth ; then
-                mm_mythdb_settings_set "DVDRipLocation" "${MM_MYTHDVD_MOUNTPOINT}/.mtd"
-                TRANSCODE=`/usr/bin/which transcode`
-                mm_mythdb_settings_set "TranscodeCommand" "${TRANSCODE}"
-                /bin/su -c "/usr/bin/mtd --daemon" - minimyth
-            else
-                /usr/bin/logger -t minimyth -p "local0.err" \
-                    "error: '${MM_MYTHDVD_MOUNTPOINT}/.mtd' exists but is not writable by user 'minimyth'."
-                exit 1
-            fi
-        else
+    if /usr/bin/test -n "${MM_MYTHDVD_MOUNTPOINT}" && /usr/bin/test -n "${MM_MYTHDVD_URL}" ; then
+        MTD=`/usr/bin/which mtd`
+        TRANSCODE=`/usr/bin/which transcode`
+        if /usr/bin/test -z "${MTD}" ; then
             /usr/bin/logger -t minimyth -p "local0.err" \
-                "error: '${MM_MYTHDVD_MOUNTPOINT}/.mtd' exists but is not a directory."
+                "error: 'mtd' not found."
             exit 1
         fi
+        if /bin/su -c "/usr/bin/test ! -e ${MM_MYTHDVD_MOUNTPOINT}" - minimyth ; then
+            /usr/bin/logger -t minimyth -p "local0.err" \
+                "error: '${MM_MYTHDVD_MOUNTPOINT}' does not exist."
+            exit 1
+        fi
+        if /bin/su -c "/usr/bin/test ! -d ${MM_MYTHDVD_MOUNTPOINT}" - minimyth ; then
+            /usr/bin/logger -t minimyth -p "local0.err" \
+                "error: '${MM_MYTHDVD_MOUNTPOINT}' is not a directory."
+            exit 1
+        fi
+        if /bin/su -c "/usr/bin/test ! -w ${MM_MYTHDVD_MOUNTPOINT}" - minimyth ; then
+            /usr/bin/logger -t minimyth -p "local0.err" \
+                "error: '${MM_MYTHDVD_MOUNTPOINT}' is not writable by user 'minimyth'."
+            exit 1
+        fi
+        /bin/su -c "/bin/mkdir -p ${MM_MYTHDVD_MOUNTPOINT}/.mtd" - minimyth
+        if /bin/su -c "/usr/bin/test ! -e ${MM_MYTHDVD_MOUNTPOINT}/.mtd" - minimyth ; then
+            /usr/bin/logger -t minimyth -p "local0.err" \
+                "error: '${MM_MYTHDVD_MOUNTPOINT}/.mtd' does not exist."
+            exit 1
+        fi
+        if /bin/su -c "/usr/bin/test ! -d ${MM_MYTHDVD_MOUNTPOINT}/.mtd" - minimyth ; then
+            /usr/bin/logger -t minimyth -p "local0.err" \
+                "error: '${MM_MYTHDVD_MOUNTPOINT}/.mtd' is not a directory."
+            exit 1
+        fi
+        if /bin/su -c "/usr/bin/test ! -w ${MM_MYTHDVD_MOUNTPOINT}/.mtd" - minimyth ; then
+            /usr/bin/logger -t minimyth -p "local0.err" \
+                "error: '${MM_MYTHDVD_MOUNTPOINT}/.mtd' is not writable by user 'minimyth'."
+            exit 1
+        fi
+        mm_mythdb_settings_set "DVDRipLocation" "${MM_MYTHDVD_MOUNTPOINT}/.mtd"
+        mm_mythdb_settings_set "TranscodeCommand" "${TRANSCODE}"
+        /bin/su -c "${MTD} --daemon" - minimyth
     fi
 
     # Configure Myth database jumppoints to match MiniMyth frontend.
