Added security     - Added PAM support.         - Added PAM.         - Enabled PAM support in busybox telnet.         - Enabled PAM support in dropbear.     - Added LDAP authentication.         - Added nss_ldap.             - Patched to override non-existent home directories and shells.         - Added pam_ldap.         - Added MM_AUTH_LDAP_* to configure LDAP authentication.     - Added SSH server (dropbear).     - Made some of the file system permissions more strict.     - Added MM_SECURITY_* to configure security.         - Disabled telnet and web access to the file system when security           is enabled.     - Added MM_AUTH_* to configure authentication. Added packages     - 'lib/openldap'     - 'system/nss_ldap'     - 'system/pam'     - 'system/pam_ldap' Patched problems in packages     - 'devel/flex'     - 'lib/openssl'

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/ssh b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/ssh
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/ssh
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/ssh
@@ -5,12 +5,24 @@
 . /etc/rc.d/functions
 
 start() {
-    mm_message_output info "configuring ssh client ..."
+    mm_message_output info "configuring ssh ..."
 
     if /usr/bin/test -e /etc/ssh/id_rsa ; then
         /bin/mkdir -p /etc/dropbear
         /usr/bin/dropbearconvert openssh dropbear /etc/ssh/id_rsa /etc/dropbear/id_rsa
-        /bin/chmod 644 /etc/dropbear/id_rsa
+        /bin/chmod 640 /etc/dropbear/id_rsa
+        /bin/chown root:ssh /etc/dropbear/id_rsa
+    fi
+
+    if /usr/bin/test "${MM_SSH_SERVER_ENABLED}" = "yes" ; then
+        if /usr/bin/test ! -n "`/bin/pidof dropbear`" ; then
+            mm_message_output info "starting ssh server ..."
+            if /usr/bin/test ! -e /etc/dropbear/id_rsa ; then
+                mm_message_output err "error: cannot not start ssh server: no host key."
+                exit 1
+            fi
+            /usr/sbin/dropbear -r /etc/dropbear/id_rsa
+        fi
     fi
 
     return 0
@@ -18,6 +30,12 @@ start() {
 
 
 stop() {
+ 
+    if /usr/bin/test -n "`/bin/pidof dropbear`" ; then
+        mm_message_output info "stopping ssh server ..."
+        /usr/bin/killall dropbear
+    fi
+
     return 0
 }
 
