- Cleaned up SSH remote command execution scripts and documentation.

diff --git a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/ssh_remote b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/ssh_remote
--- a/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/ssh_remote
+++ b/trunk/gar-minimyth/script/meta/minimyth/dirs/etc/rc.d/init.d/ssh_remote
@@ -26,10 +26,20 @@ start() {
 
     if /usr/bin/test "${MM_SSH_REMOTE_ENABLED}" = "yes" ; then
         if /usr/bin/test "${MM_MYTHSTREAM_ENABLED}" = "yes" ; then
-            mm_ssh_remote_put /dev/null /usr/share/mythtv/mythstream/parsers
+            mkdir -p /var/log
+            mm_ssh_remote_put /var/log/init_ssh_remote.log /usr/share/mythtv/mythstream/parsers
+            if /usr/bin/test $? -ne 0 ; then
+                mm_message_output err "error: failed to copy MythStream parsers to remote host. see /var/log/init_ssh_remote.log for more details."
+                exit 1
+            fi
         fi
         if /usr/bin/test "${MM_MYTHVIDEO_ENABLED}" = "yes" ; then
-            mm_ssh_remote_put /dev/null /usr/share/mythtv/mythvideo/scripts
+            mkdir -p /var/log
+            mm_ssh_remote_put /var/log/init_ssh_remote.log /usr/share/mythtv/mythvideo/scripts
+            if /usr/bin/test $? -ne 0 ; then
+                mm_message_output err "error: failed to copy MythVideo scripts to remote host. see /var/log/init_ssh_remote.log for more details."
+                exit 1
+            fi
         fi
     fi
 
